# -*- coding: utf-8 -*-
# 101-125 批次详细标注（合并进 master.json learn.enh）
ENH = {
101: {"fullIpa":"/aɪd laɪk tə tʃɛk ɪn fɔr ðə ˈtɛn ˌeɪˈɛm flaɪt tu ˈlʌndən/",
 "variants":[["I'm here to check in for the ten a.m. flight.","开场直说，柜台常用"],["Checking in for the London flight, please.","报目的地省时间"],["Ten a.m. to London, please.","极简报航班"]],
 "scenes":[["值机柜台","I'd like to check in for the ten a.m. flight to London.","地勤回 May I see your passport? / Any bags to check?"],["自动柜台求助","Could you help me with the kiosk? I'm on the ten a.m. to London.","工作人员过来帮你操作"],["确认航班号","Flight BA117, is that the ten o'clock?","确认航班号与时间"]],
 "grammar":"I'd like to + 动词原形是最万能的礼貌开场（= I would like to）；check in 固定短语『办理值机』，中间不加冠词；a.m. 前用 the；flight to + 城市表『飞往…的航班』。",
 "pron":"缩读：I'd = I would（/aɪd/）。连读：like to→/laɪk tə/（可并作 /laɪktə/）；check in→/tʃɛ kɪn/（k 与 ɪ）；ten a.m.→/ˈtɛn eɪɛm/（n 与 e）；flight to→/flaɪt tu/（t 与 t 只读一次）。弱读：to→/tə/；for→/fər/。失去爆破：flight to 中 /t/ 不完全爆破 /flaɪ(t) tu/。浊化：无典型。"},
102: {"fullIpa":"/ɪz ðer ə ˌsɛlfˈsɜrvɪs ˈkiːɑsk əˈraʊnd hɪr/",
 "variants":[["Is there a kiosk nearby?","省 self-service 也懂"],["Where's the self-service kiosk?","直接问位置"],["Can I check in at a machine?","换说法，机器值机"]],
 "scenes":[["机场问路","Is there a self-service kiosk around here?","工作人员回 Yes, right beside the counters. / Down the hall to your left."],["酒店场景复用","Is there a self-check-in kiosk?","酒店自助机也这么说"],["排队太久想换自助","Can I use the kiosk instead?","地勤指给你自助区"]],
 "grammar":"Is there a/an + 单数名词 一般疑问句；self-service 复合形容词（self- 自身 + service 服务）；around here = 这附近（比 here 更口语）。",
 "pron":"连读：Is there a→/ɪz ðer ə/（词间元音顺接）；self-service→/ˌsɛlf ˈsɜrvɪs/（f 与 s 相邻轻擦）；around here→/əˈraʊnd hɪr/（d 与 h 连读）。弱读：a→/ə/。失去爆破：kiosk 词尾 /k/ 轻微。浊化：无。同化：无典型。"},
103: {"fullIpa":"/kʊd aɪ ɡɛt ə ˈwɪndoʊ siːt ðɪs taɪm/",
 "variants":[["A window seat, please.","极简点单式"],["Do you have any window seats left?","问有没有"],["Any chance of a window seat?","口语化碰运气问法"]],
 "scenes":[["值机选座","Could I get a window seat this time?","地勤回 Let me see… Yes, 24A is free. / Only middle seats left."],["换座","Could I switch to a window seat?","登机口再试一次"],["同伴商量","I'll take the aisle if you get the window.","一个靠窗一个过道"]],
 "grammar":"Could I… 比 Can I 更客气；get 表『得到、安排』比 have 更活；this time 这一次（暗示上次不是靠窗）；window seat / aisle seat / middle seat 三种座位固定说法。",
 "pron":"连读：Could I→/kʊ daɪ/（d 与 aɪ 顺连）；get a→/ɡɛ tə/（t 与 ə）；seat this→/siːt ðɪs/（t 与 ð）；this time→/ðɪs taɪm/（s 与 t 相邻轻擦）。弱读：a→/ə/。同化：this time 快读 /s/ 与 /t/ 相邻产生轻微 /s/ 拖音。失去爆破：seat this /siː(t) ðɪs/。"},
104: {"fullIpa":"/du aɪ niːd tə tʃɛk ɪn ɑnˈlaɪn bɪˈfɔrhænd/",
 "variants":[["Should I check in online first?","should 带建议意味"],["Can I check in online?","问能不能"],["Is online check-in required?","正式问是否必须"]],
 "scenes":[["出发前查攻略","Do I need to check in online beforehand?","常被建议 Yes, it saves time at the airport."],["航空电话客服","Do I have to check in online for this flight?","客服告知规则"],["到机场补救","I didn't check in online, is that a problem?","柜台通常仍可办理"]],
 "grammar":"Do I need to + 动词原形 问『需要…吗』；check in online 语序（副词 online 后置）；beforehand 副词『事先』= in advance / ahead of time。",
 "pron":"连读：need to→/niː tə/（d 与 t 只读一次，可作 /niːtə/）；check in→/tʃɛ kɪn/；in online→/ɪ nɑnˈlaɪn/（顺接）。弱读：to→/tə/。失去爆破：need to /niː(d) tə/。浊化：无。重音：beforehand 重音在 fore /bɪˈfɔrhænd/。"},
105: {"fullIpa":"/wʌts ðə ˈbæɡɪdʒ əˈlaʊəns fər ɪˈkɑnəmi klæs/",
 "variants":[["How much luggage can I bring?","口语最常用"],["What's the checked baggage limit?","专问托运额度"],["How many kilos are allowed?","直问公斤数"]],
 "scenes":[["值机前确认","What's the baggage allowance for economy class?","地勤回 23 kilos for checked bags, 8 for carry-on."],["超重现场","Is my bag over the allowance?","称重后告知"],["买票前看规则","What's the baggage allowance on this ticket?","购票页或客服查询"]],
 "grammar":"allowance 名词『限额』（allow 允许 → allowance）；baggage 美式（英式常用 luggage），不可数；economy class 机舱等级（还有 business / first class）。",
 "pron":"同化：What's the→/wʌts ðə/（ts 与 ð 相邻）；连读：allowance for→/əˈlaʊəns fər/（s 与 f）；for economy→/fər ɪˈkɑnəmi/（r 与 ɪ 加滑音）。弱读：the→/ðə/；for→/fər/。重音：allowance /əˈlaʊəns/、economy /ɪˈkɑnəmi/ 都是第二音节重读。"},
106: {"fullIpa":"/ðə ˈtʃɛkɪn ˈkaʊntər ˈkloʊzɪz ˈfɔrti ˈmɪnɪts bɪˈfɔr dɪˈpɑrtʃər/",
 "variants":[["Check-in closes forty minutes before the flight.","省 the，更泛指"],["The counter shuts forty minutes prior to departure.","prior to 更正式"],["You need to check in at least forty minutes early.","换个角度说"]],
 "scenes":[["广播听到确认","The check-in counter closes forty minutes before departure.","确认自己赶得上"],["提醒同伴","We should hurry, check-in closes forty minutes early.","催促出发"],["改签咨询","I arrived late and the counter had closed.","解释误机原因"]],
 "grammar":"close 做动词『关闭』（closed 过去式）；before departure 介词短语作时间；forty minutes before… 数量+时间+before 结构；departure /dɪˈpɑrtʃər/ 是 depart 的名词形式。",
 "pron":"连读：counter closes→/ˈkaʊntər ˈkloʊzɪz/（r 与 k 加滑音）；closes forty→/ˈkloʊzɪz ˈfɔrti/（z 与 f）；before departure→/bɪˈfɔr dɪˈpɑrtʃər/（r 与 d）。失去爆破：forty minutes /ˈfɔr(t)i ˈmɪnɪts/（t 在 m 前不完全爆破）；before departure /bɪˈfɔr dɪˈpɑrtʃər/（r 可轻微连）。重音：forty /ˈfɔrti/、minutes /ˈmɪnɪts/。"},
107: {"fullIpa":"/kæn aɪ peɪ fɔr ði ˈɛkstrə bæɡ ət ðə ˈkaʊntər/",
 "variants":[["Can I pay for the overweight bag here?","overweight 更专业"],["Where do I pay for the extra bag?","问付款位置"],["Is there a fee for the extra bag?","先问要不要钱"]],
 "scenes":[["柜台超重","Can I pay for the extra bag at the counter?","地勤回 Yes, card or cash? / That'll be 60 dollars."],["自助机付款","Can I pay the excess baggage fee at the kiosk?","机器支持超重付款"],["事后补缴","I already paid for my extra bag online.","出示缴费凭证"]],
 "grammar":"pay for + 名词『为…付钱』（pay the fee 直接加宾语也行）；extra bag 超件/超重行李（规范说法 excess baggage）；at the counter 在柜台（用 at）。",
 "pron":"连读：Can I→/kæ naɪ/；pay for→/peɪ fər/（eɪ 与 f）；for the→/fər ðə/；extra bag→/ˈɛkstrə bæɡ/（r 与 b 加滑音）；at the→/ət ðə/。弱读：for→/fər/；at→/ət/。失去爆破：extra bag 中 /r/ 连读；counter /ˈkaʊntər/ 词尾轻。重音：extra /ˈɛkstrə/ 在前。"},
108: {"fullIpa":"/ɪz ðə flaɪt ɑn ˈskɛdʒuːl təˈdeɪ/",
 "variants":[["Is the flight on time?","最常用说法"],["Is my flight delayed?","直问延误"],["Any delays on the London flight?","问特定航班"]],
 "scenes":[["值机时问","Is the flight on schedule today?","地勤回 So far on time. / There's a thirty-minute delay."],["登机口问","Are we still on schedule?","确认起飞状态"],["电话问机场","Is flight CX250 on schedule today?","报航班号询问"]],
 "grammar":"on schedule 固定短语『准点』（= on time）；schedule 美式 /ˈskɛdʒuːl/ 英式 /ˈʃɛdjuːl/；today 句尾表今天这趟。",
 "pron":"连读：Is the→/ɪz ðə/（z 与 ð）；flight on→/flaɪt ɑn/（t 与 ɑ 元音间加轻爆破）；on schedule→/ɑn ˈskɛdʒuːl/（n 与 s）。弱读：the→/ðə/。失去爆破：flight on /flaɪ(t) ɑn/。重音：schedule 重音在第一音节。"},
109: {"fullIpa":"/aɪ hæv ə kəˈnɛktɪŋ flaɪt tu tʃɛtʃ æt eɪt/",
 "variants":[["I have a tight connection at eight.","tight connection 转机紧"],["My connecting flight leaves at eight.","说全句"],["I'm catching a connecting flight at eight.","catch 强调赶"]],
 "scenes":[["请地勤帮忙","I have a connecting flight to catch at eight.","请求优先/快走廊桥"],["要求前排座位","Could I get a seat near the front? I have a tight connection.","落地快下机"],["下机问路","Where's the gate for my connecting flight?","问转机登机口"]],
 "grammar":"to catch 不定式作后置定语（flight to catch 要赶的航班）；connecting 现在分词作定语『衔接的』；catch a flight 固定搭配『赶航班』。",
 "pron":"连读：have a→/hæv ə/（v 与 ə）；flight to→/flaɪt tə/（t 与 t，只读一次）；to catch→/tə kætʃ/（ə 与 k）；catch at→/kætʃ æt/（tʃ 与 æ）。弱读：a→/ə/；to→/tə/。失去爆破：flight to /flaɪ(t) tə/。缩读注意：at eight 连读 /æt eɪt/（t 与 eɪ）。"},
110: {"fullIpa":"/wɛr ʃʊd aɪ ɡoʊ fɔr maɪ ˈtrænsfɜr/",
 "variants":[["Where do I go for my transfer?","do 比 should 直接"],["Which way for transfers?","极简看指示牌问法"],["I'm transferring to Osaka, where to?","先报目的地"]],
 "scenes":[["下机后问工作人员","Where should I go for my transfer?","回 Follow the signs to Connections. / Take the train to Terminal 2."],["问同机旅客","Are you transferring too? Which way?","结伴找路"],["免税店前犹豫","Excuse me, transfers this way?","手势+简短确认"]],
 "grammar":"should 表求建议；transfer 此处名词『转机』（也可动词 transfer to…）；for 表目的。",
 "pron":"连读：Where should I→/wɛr ʃʊ daɪ/（r 与 ʃ；d 与 aɪ）；go for→/ɡoʊ fər/（oʊ 与 f）；for my→/fər maɪ/。弱读：should→/ʃʊ/；for→/fər/。失去爆破：go for /ɡoʊ (f)ər/ 轻微。重音：transfer 名词 /ˈtrænsfɜr/ 重音在前。"},
111: {"fullIpa":"/du aɪ niːd tu pɪk ʌp maɪ ˈlʌɡɪdʒ ənd tʃɛk ɪt ɪn əˈɡɛn/",
 "variants":[["Do I have to recheck my baggage?","recheck 一个词搞定"],["Is my luggage checked through?","问是否直挂"],["Will my bag go all the way through?","口语化问直挂"]],
 "scenes":[["转机咨询","Do I need to pick up my luggage and check it in again?","地勤回 No, it's checked through to your final destination. / Yes, you must recheck it here."],["不同航司联程","I booked separately, do I need to recheck?","分开买票通常要重新托运"],["入境美国/澳洲特别提醒","Do I have to claim and recheck at the first stop?","美澳转机必取行李"]],
 "grammar":"pick up 固定短语『领取/取走』；check in again = recheck；need to + 原形。注意 luggage 不可数。",
 "pron":"连读：need to→/niːtə/；pick up→/pɪ kʌp/（k 与 ʌ）；up my→/ʌp maɪ/；and check→/ən tʃɛk/（d 失去）；check it→/tʃɛ kɪt/（k 与 ɪ）；it in→/ɪ tɪn/；in again→/ɪ nəˈɡɛn/。弱读：and→/ən/；to→/tə/；it→/ɪt/。失去爆破：up my /ʌ(p) maɪ/。"},
112: {"fullIpa":"/haʊ mʌtʃ ˈleɪoʊvər taɪm du aɪ hæv bɪˈtwin ðə flaɪts/",
 "variants":[["How long is my layover?","最简洁"],["How much time between flights?","口语省略"],["Is my layover long enough?","直接问够不够"]],
 "scenes":[["订票看行程","How much layover time do I have between the flights?","行程单显示 2h35m"],["担心转机","Is two hours enough for the layover?","求安心"],["落地后看时间","My layover is only fifty minutes!","发现自己要跑"]],
 "grammar":"layover 美式『中转停留』（英式 stopover 指更长停留）；How much + 不可数（time）；between the flights 在两班之间。",
 "pron":"连读：How much→/haʊ mʌtʃ/（w 与 m）；much layover→/mʌtʃ ˈleɪoʊvər/（tʃ 与 l）；do I→/du aɪ/；have between→/hæv bɪˈtwiːn/（v 与 b）；between the→/bɪˈtwiːn ðə/（n 与 ð）。弱读：do→/də/；the→/ðə/。重音：layover /ˈleɪoʊvər/ 在前。"},
113: {"fullIpa":"/ɪz wʌn ˈaʊər ɪˈnʌf fɔr ðə kəˈnɛkʃən/",
 "variants":[["Is an hour enough to make the connection?","make 表赶上"],["Will an hour be enough for my connection?","将来时稳妥"],["Can I make it in an hour?","口语自问式"]],
 "scenes":[["订票咨询客服","Is one hour enough for the connection?","客服回 It's tight but doable if the first flight is on time."],["改签决策","Should I take the earlier one? One hour seems risky.","权衡换航班"],["求地勤协助","I only have an hour, what's the fastest way?","问快速通道"]],
 "grammar":"connection 此处指『联程衔接』；make the connection 固定搭配『赶上转机』；enough for + 名词。",
 "pron":"连读：one hour→/wʌn ˈaʊər/（n 与 aʊ）；hour enough→/ˈaʊər ɪˈnʌf/（r 与 ɪ）；enough for→/ɪˈnʌf fər/（f 与 f 只读一次轻擦）；for the→/fər ðə/。弱读：for→/fər/；the→/ðə/。重音：connection /kəˈnɛkʃən/ 第二音节。"},
114: {"fullIpa":"/aɪ mɪst maɪ kəˈnɛkʃən bɪˈkɔz əv ðə dɪˈleɪ/",
 "variants":[["The delay made me miss my connecting flight.","换主语说法"],["I didn't make my connection due to the delay.","due to 更正式"],["My connection was missed because of you.","对航司索赔口径"]],
 "scenes":[["到服务台改签","I missed my connection because of the delay.","客服回 We'll rebook you on the next available flight."],["报保险","My connecting flight was missed due to a three-hour delay.","索赔陈述"],["向接机人解释","Sorry I'm late, I missed my connection in Paris.","电话告知"]],
 "grammar":"missed 过去式；because of + 名词（because + 句子）；connection 指转机航班。",
 "pron":"连读：I missed my→/aɪ mɪst maɪ/（t 与 m）；because of the→/bɪˈkɔz əv ðə/（z 与 ə；v 与 ð）；of the delay→/əv ðə dɪˈleɪ/。弱读：of→/əv/；the→/ðə/。失去爆破：missed my /mɪs(t) maɪ/（t 在 m 前不完全爆破）。重音：because /bɪˈkɔz/、delay /dɪˈleɪ/。"},
115: {"fullIpa":"/wɪl ðə ˈerlaɪn pʊt miː ɑn ðə nɛkst flaɪt fɔr friː/",
 "variants":[["Will you rebook me on the next flight for free?","直接对航司说"],["Am I entitled to a free rebooking?","entitle 问权利"],["Can I get on the next flight at no charge?","at no charge 换法"]],
 "scenes":[["改签柜台","Will the airline put me on the next flight for free?","客服回 If it's our delay, yes, free of charge."],["非联程票询问","I missed it because I booked separately, can you still help?","自担责任情形"],["要求书面确认","Could I get that in writing, the free rebooking?","留证据"]],
 "grammar":"put sb. on + 航班『把某人安排到…航班』；for free 免费地（= free of charge）；airline 单数指航空公司（英式常用复数 the airline's）。",
 "pron":"连读：Will the→/wɪl ðə/；put me→/pʊt miː/（t 与 m）；me on→/miː ɑn/（iː 与 ɑ 顺连）；on the→/ɑn ðə/；next flight→/nɛkst flaɪt/（st 与 f）；flight for→/flaɪt fər/。弱读：the→/ðə/；for→/fər/。失去爆破：put me /pʊ(t) miː/；next flight /nɛks(t) flaɪt/。"},
116: {"fullIpa":"/ɪz ðer ˈɛni ˌkɑmpenˈseɪʃən fɔr ðə dɪˈleɪd flaɪt/",
 "variants":[["Am I entitled to compensation for the delay?","entitle 维权用语"],["Will I get anything for the delay?","口语化"],["What compensation do you offer for delays?","问政策"]],
 "scenes":[["延误现场问","Is there any compensation for the delayed flight?","客服回 For delays over three hours, EU rules apply."],["事后索赔","I'd like to claim compensation for flight BA117.","正式提交"],["拿代金券","Are meal vouchers provided?","先解决吃饭"]],
 "grammar":"compensation 不可数名词『补偿』；delayed 过去分词作定语『被延误的』；Is there any + 不可数/复数。",
 "pron":"连读：Is there any→/ɪz ðer ˈɛni/（词间顺接）；compensation for→/ˌkɑmpenˈseɪʃən fər/（n 与 f）；for the→/fər ðə/；the delayed flight→/ðə dɪˈleɪd flaɪt/（d 与 f）。弱读：for→/fər/；the→/ðə/。重音：compensation 重音在 pen /ˌkɑmpenˈseɪʃən/。"},
117: {"fullIpa":"/haʊ lɔŋ ɪz ðə flaɪt ɪkˈspɛktɪd tə bi dɪˈleɪd/",
 "variants":[["How long is the delay expected to be?","宾语从句版"],["What's the new departure time?","问新起飞时间"],["When will we know more?","问信息更新"]],
 "scenes":[["登机口问乘务","How long is the flight expected to be delayed?","回 We're waiting for an update, maybe an hour."],["广播没听清问邻座","Did they say how long the delay is?","复述确认"],["改高铁决策","If it's more than two hours I'll take the train.","设定底线"]],
 "grammar":"be expected to be + 过去分词『预计被…』被动结构；delay 被动语态。",
 "pron":"连读：How long is→/haʊ lɔŋ ɪz/（ŋ 与 ɪ）；is the→/ɪz ðə/；flight is→/flaɪt ɪz/（t 与 ɪ 连读加轻爆破）；expected to be→/ɪkˈspɛktɪd tə bi/（d 与 t 只读一次）；to be delayed→/tə bi dɪˈleɪd/。弱读：to→/tə/；be→/bi/。失去爆破：expected to /ɪkˈspɛk(tɪ)d tə/。"},
118: {"fullIpa":"/wɛr kæn aɪ kleɪm maɪ tʃɛkt ˈlʌɡɪdʒ/",
 "variants":[["Where's baggage claim?","极简标牌用语"],["Where do I pick up my checked bags?","pick up 换法"],["Which carousel is for flight BA117?","直接问转盘号"]],
 "scenes":[["落地问路","Where can I claim my checked luggage?","回 Down the escalator, follow the signs for baggage claim."],["找转盘","Which carousel is BA117?","看屏幕核对"],["等很久没出来","Has baggage from BA117 come out yet?","确认批次"]],
 "grammar":"claim 动词『认领』；checked luggage 托运行李（过去分词作定语）；Where can I + 动词原形问地点。",
 "pron":"连读：Where can I→/wɛr kæ naɪ/；can I claim→/kæ naɪ kleɪm/（aɪ 与 k）；claim my→/kleɪm maɪ/（m 与 m 相连只读一次）；my checked→/maɪ tʃɛkt/（aɪ 与 tʃ）。弱读：can→/kən/。失去爆破：checked luggage /tʃɛk(t) ˈlʌɡɪdʒ/（t 在 l 前不完全爆破）。"},
119: {"fullIpa":"/wʌn əv maɪ ˈsuːtkeɪsɪz dɪdənt kʌm aʊt/",
 "variants":[["One of my bags is missing.","missing 更简"],["One of my suitcases hasn't arrived.","完成时正式"],["I can't find one of my suitcases.","找的角度说"]],
 "scenes":[["行李转盘旁","One of my suitcases didn't come out.","工作人员带你去 lost baggage counter"],["报失登记","My black Samsonite didn't show up.","描述特征登记"],["同机旅客互相确认","Is this carousel for our flight?","排除站错地方"]],
 "grammar":"One of + 复数名词『其中一个』（后动词用单数）；didn't come out 过去式否定；come out 固定搭配『出来』（行李语境=被送出）。",
 "pron":"连读：One of my→/wʌn əv maɪ/（n 与 ə；v 与 m）；of my suitcases→/əv maɪ ˈsuːtkeɪsɪz/；didn't come out→/ˈdɪdənt kʌm aʊt/（nt 与 k；m 与 aʊ）。缩读：didn't = did not /ˈdɪdənt/。失去爆破：didn't come /ˈdɪdən(t) kʌm/。"},
120: {"fullIpa":"/maɪ ˈlʌɡɪdʒ siz tə bi ˈdæmɪdʒd/",
 "variants":[["My suitcase is damaged.","直接肯定句"],["There's a big crack in my luggage.","具体描述损坏"],["My bag got damaged on the flight.","指明环节"]],
 "scenes":[["报损登记","My luggage seems to be damaged.","工作人员拍照登记并给单据"],["理赔说明","The wheel broke off and there's a tear.","具体伤情"],["当场开箱检查","Can I check the contents? It looks badly hit.","怕内容物碎"]],
 "grammar":"seem to be + 形容词/过去分词『似乎处于…状态』（比 is 语气弱、留余地）；damaged 过去分词作表语。",
 "pron":"连读：luggage seems→/ˈlʌɡɪdʒ siːmz/（dʒ 与 s）；seems to be→/siːmz tə bi/（z 与 t）；to be damaged→/tə bi ˈdæmɪdʒd/（i 与 d）。弱读：to→/tə/；be→/bi/。失去爆破：seems to /siːm(z) tə/ 轻微。重音：damaged /ˈdæmɪdʒd/ 在前。"},
121: {"fullIpa":"/kʊd ju hɛlp mi lɪft ðɪs bæɡ ˈɑntu ðə bɛlt/",
 "variants":[["Could you give me a hand with this bag?","give a hand 万能求助"],["Can someone help me lift this?","求人不限对象"],["This is too heavy for me, could you help?","先示弱再求助"]],
 "scenes":[["值机柜台","Could you help me lift this bag onto the belt?","地勤或旁边旅客搭手"],["火车站安检","Could you help me get this onto the scanner?","安检处复用"],["互助","Let me give you a hand with that.","主动帮人时说"]],
 "grammar":"help sb. (to) do 结构；onto 表『到…上面』（on + to 合成）；lift 及物动词『抬起』。",
 "pron":"同化：Could you→/kʊdʒu/（d+j 同化为 dʒ，关键！）。连读：help me→/hɛlp miː/（p 与 m）；me lift→/mi lɪft/（i 与 l）；lift this→/lɪft ðɪs/（t 与 ð）；this bag→/ðɪs bæɡ/（s 与 b）；onto the→/ˈɑntə ðə/。弱读：you→/jə/；the→/ðə/。失去爆破：lift this /lif(t) ðɪs/。"},
122: {"fullIpa":"/ɪz ðer ə ˈtrɑli aɪ kæn juz ˈnɪrbaɪ/",
 "variants":[["Where can I get a trolley?","直接问位置"],["Is there a cart I can use?","美式 cart"],["Do the trolleys need coins?","问要不要投币"]],
 "scenes":[["行李大厅","Is there a trolley I can use nearby?","回 Yes, stacked by the pillars. / They need a one-euro coin."],["没零钱投币","Could you break a ten for the trolley?","换硬币"],["用完归还","Where do I return the trolley?","问归还点"]],
 "grammar":"a trolley (that) I can use 省略 that 的定语从句；nearby 副词句尾『在附近』；trolley 英式/欧陆，cart 美式。",
 "pron":"连读：Is there a→/ɪz ðer ə/；trolley I→/ˈtrɑli aɪ/（i 与 aɪ 顺连）；I can use→/aɪ kən juz/；use nearby→/juz ˈnɪrˌbaɪ/（z 与 n）。弱读：can→/kən/；a→/ə/。重音：trolley /ˈtrɑli/、nearby 重音在 near。"},
123: {"fullIpa":"/aɪd laɪk tu rɪˈpɔrt ə lɔst ˈsuːtkeɪs pliz/",
 "variants":[["I'd like to report my suitcase missing.","missing 后置"],["My suitcase didn't arrive.","现象描述开局"],["I need to file a lost luggage report.","file a report 正式"]],
 "scenes":[["报失柜台","I'd like to report a lost suitcase, please.","工作人员要护照、行李票并填表"],["描述特征","It's a dark blue hard-shell, about this big.","比划描述"],["取回方式","How will I know when it's found?","问通知流程"]],
 "grammar":"report + 名词『申报/报案』；lost 过去分词作定语；I'd like to 礼貌开场。",
 "pron":"缩读：I'd = I would /aɪd/。连读：like to→/laɪktə/；to report a→/tə rɪˈpɔrt ə/（t 与 r；t 与 ə）；report a lost→/rɪˈpɔrt ə lɔst/；a lost suitcase→/ə lɔst ˈsuːtkeɪs/。弱读：to→/tə/；a→/ə/。失去爆破：lost suitcase /lɔs(t) ˈsuːtkeɪs/。"},
124: {"fullIpa":"/hɪrz maɪ kleɪm tæɡ fɔr ðə ˈmɪsɪŋ bæɡ/",
 "variants":[["Here's the claim tag for my missing bag.","the 特指"],["This is my baggage tag.","简单出示"],["I have the tags right here.","复数出示"]],
 "scenes":[["报失核对","Here's my claim tag for the missing bag.","工作人员撕下副联核对系统"],["多件行李比对","These two arrived but this one didn't.","并排说明"],["领取找回行李","I'm here to pick up my found bag, here's the tag.","取件时用"]],
 "grammar":"Here's = Here is（倒装强调递出）；claim tag 固定搭配『（行李）提取/报失凭条』；for 表对应关系。",
 "pron":"缩读：Here's = Here is /hɪrz/。连读：Here's my→/hɪrz maɪ/（z 与 m）；claim tag→/kleɪm tæɡ/（m 与 t）；tag for the→/tæɡ fər ðə/；for the missing→/fər ðə ˈmɪsɪŋ/；the missing bag→/ðə ˈmɪsɪŋ bæɡ/。弱读：for→/fər/；the→/ðə/。失去爆破：claim tag /kleɪ(m) tæɡ/ 轻微。"},
125: {"fullIpa":"/ˈpæspɔrt ənd ˈbɔrdɪŋ pæs pliz/",
 "variants":[["Passport and ticket, please.","老派说法含机票"],["May I see your passport and boarding pass?","完整礼貌版"],["Documents, please.","查证件泛指"]],
 "scenes":[["安检/登机口","Passport and boarding pass, please.","你递上证件"],["边检官员","Passport, please. What's the purpose of your visit?","顺势回答"],["酒店入住","Passport, please, for check-in.","前台复用"]],
 "grammar":"省略句：May I see your… 的口语缩略（祈使语气但加 please 保持礼貌）；and 连接两个并列宾语。",
 "pron":"连读：Passport and→/ˈpæspɔrt ən/（t 失去）；and boarding→/ən ˈbɔrdɪŋ/（n 与 b）；boarding pass→/ˈbɔrdɪŋ pæs/（ŋ 与 p）。弱读：and→/ən/。失去爆破：Passport and /ˈpæspɔr(t) ən/。注意：boarding 重音在前 /ˈbɔrdɪŋ/，pass 短促。"},
}
