# -*- coding: utf-8 -*-
# 126-150 批次详细标注（合并进 master.json learn.enh）
ENH = {
126: {"fullIpa":"/du aɪ niːd tu teɪk maɪ ˈlæptɑp aʊt əv ðə bæɡ/",
 "variants":[["Do I need to take out my laptop?","省略 of 短语"],["Should my laptop come out?","被动问法"],["Laptop out?","最简手势配合"]],
 "scenes":[["安检问安检员","Do I need to take my laptop out of the bag?","回 Yes, in a separate tray please. / No, it can stay if it's a small bag."],[" liquids 一起问","Do the liquids need to come out too?","一并确认"],["排队学别人","He took his out, should I?","照做前确认"]],
 "grammar":"take A out of B 固定搭配『把 A 从 B 拿出』；need to + 原形；laptop 笔记本电脑（美），英式也说 notebook。",
 "pron":"连读：need to→/niːtə/；to take my→/tə teɪk maɪ/；take my→/teɪk maɪ/（k 与 m）；my laptop→/maɪ ˈlæptɑp/（aɪ 与 l）；out of the→/aʊt əv ðə/（t 失去）；of the bag→/əv ðə bæɡ/。弱读：to→/tə/；of→/əv/；the→/ðə/。失去爆破：take my /teɪ(k) maɪ/；out of /aʊ(t) əv/。"},
127: {"fullIpa":"/pliz pʊt jʊr ˈlɪkwɪdz ɪn ðɪs treɪ/",
 "variants":[["Liquids in the tray, please.","标牌式简语"],["Take out your liquids for screening.","screening 更专业"],["All liquids go in the tray.","通用指令"]],
 "scenes":[["安检员指示","Please put your liquids in this tray.","照做即可"],["询问尺寸","Does my toothpaste count as a liquid?","膏体也算液体"],["准备透明袋","Where can I get a zip-lock bag?","机场常免费提供"]],
 "grammar":"put A in B 固定搭配；liquids 此处名词复数泛指液体物品；this tray 指定托盘。",
 "pron":"连读：Please put your→/pliz pʊt jʊr/（s 与 p；t 与 j）；put your→/pʊtʃʊr/（t+j 同化为 tʃ，关键！）；your liquids→/jʊr ˈlɪkwɪdz/（r 与 l）；liquids in→/ˈlɪkwɪdz ɪn/（z 与 ɪ）；in this→/ɪn ðɪs/（n 与 ð）；this tray→/ðɪs treɪ/（s 与 t）。同化：put your→/pʊtʃʊr/。弱读：your→/jər/。"},
128: {"fullIpa":"/æm aɪ əˈlaʊd tu brɪŋ ðɪs ˈwɔtər ˈbɑtəl θruː/",
 "variants":[["Can I bring this water through?","can 口语化"],["Is this water bottle allowed?","被动问法"],["Will this be a problem at security?","迂回问法"]],
 "scenes":[["安检前问","Am I allowed to bring this water bottle through?","安检员回 You can empty it first, or finish it now. / No liquids over 100ml."],["买水后过检","I'll chug it now, okay?","当场喝完"],["空瓶确认","It's empty, is that fine?","空瓶通常放行"]],
 "grammar":"be allowed to + 动词原形『被允许做』；bring…through 副词 through 表『带过去』。",
 "pron":"连读：Am I allowed→/æm aɪ əˈlaʊd/（m 与 aɪ）；I allowed to→/aɪ əˈlaʊd tə/（d 与 t 只读一次）；to bring this→/tə brɪŋ ðɪs/；bring this→/brɪŋ ðɪs/（ŋ 与 ð）；this water bottle→/ðɪs ˈwɔtər ˈbɑtəl/；bottle through→/ˈbɑtəl θruː/（l 与 θ）。弱读：to→/tə/。失去爆破：allowed to /əˈlaʊ(d) tə/。闪音：water 美式 /ˈwɔɾɚ/（t 闪音 /ɾ/，关键！）。"},
129: {"fullIpa":"/wʌts ðə ˈpɜrpəs əv jʊr ˈvɪzɪt/",
 "variants":[["What's the purpose of your trip?","trip 换 visit"],["Business or pleasure?","二选一极简"],["What brings you here?","口语友好版"]],
 "scenes":[["边检官员","What's the purpose of your visit?","回答 Tourism. / I'm here on business. / Visiting family."],["提前演练","He'll ask about the purpose of my visit.","过境前模拟"],["如实简洁","Sightseeing for a week.","短答不啰嗦"]],
 "grammar":"What's = What is；purpose of + 名词『…的目的』；visit 此处名词『（一次）到访』。",
 "pron":"连读：What's the→/wʌts ðə/（ts 与 ð 相邻）；the purpose of→/ðə ˈpɜrpəs əv/；purpose of your→/ˈpɜrpəs əv jʊr/（s 与 ə；v 与 j）；of your visit→/əv jʊr ˈvɪzɪt/。弱读：of→/əv/；your→/jər/；the→/ðə/。失去爆破：purpose of /ˈpɜrpə(s) əv/ 轻微。重音：purpose /ˈpɜrpəs/、visit /ˈvɪzɪt/ 都在前。"},
130: {"fullIpa":"/aɪm hɪr fɔr ˈtʊrɪzəm fɔr əˈbaʊt ə wiːk/",
 "variants":[["I'm a tourist, staying about a week.","tourist 自称"],["Just traveling for a week.","just 开头随和"],["Tourism, for seven days.","边检极简答"]],
 "scenes":[["回答边检","I'm here for tourism for about a week.","官员点头或追问 Where will you be staying?"],["补充材料","Here's my hotel booking.","主动出示"],["延长停留","I might extend to ten days, is that possible?","询问延期"]],
 "grammar":"be here for + 名词『为…而来』；tourism 不可数『旅游（目的）』；about + 数量『大约』。",
 "pron":"连读：I'm here for→/aɪm hɪr fər/（r 与 f）；here for tourism→/hɪr fər ˈtʊrɪzəm/（r 与 f；r 与 t）；for about a→/fər əˈbaʊt ə/；about a week→/əˈbaʊt ə wiːk/（t 失去）。弱读：for→/fər/；a→/ə/。缩读：I'm = I am /aɪm/。失去爆破：about a /əˈbaʊ(t) ə/。"},
131: {"fullIpa":"/haʊ lɔŋ wɪl ju bi ˈsteɪɪŋ ɪn ðə ˈkʌntri/",
 "variants":[["How long are you staying?","现在进行时表将来，最常用"],["How long is your stay?","名词问法"],["When do you leave?","问离境日"]],
 "scenes":[["边检问答","How long will you be staying in the country?","回答 Ten days. / Until the fifteenth."],["酒店前台复用","How long will you be staying with us?","回答晚数"],["不确定时","About a week, maybe ten days.","给区间"]],
 "grammar":"will be doing 将来进行时表『将会持续多久』（比 will stay 更自然）；the country 指当前所在国。",
 "pron":"连读：How long will→/haʊ lɔŋ wɪl/（ŋ 与 w）；will you be→/wɪl ju bi/（l 与 j）；you be staying→/ju bi ˈsteɪɪŋ/；be staying in→/bi ˈsteɪɪŋ ɪn/（ŋ 与 ɪ）；staying in the→/ˈsteɪɪŋ ɪn ðə/；in the country→/ɪn ðə ˈkʌntri/（n 与 ð）。弱读：will→/wəl/ 可轻读。重音：country /ˈkʌntri/ 在前。"},
132: {"fullIpa":"/hɪr ɑr maɪ ˈpæspɔrt ənd rɪˈtɜrn ˈtɪkɪt/",
 "variants":[["Here's my passport and my return ticket.","单数逐件递"],["This is my passport, and here's the return flight.","边说边分开递"],["Passport and return ticket, here you go.","here you go 收尾"]],
 "scenes":[["边检窗口","Here are my passport and return ticket.","官员翻看并扫描"],["要求补材料","Anything else? Hotel booking?","主动配合"],["复印件备用","Would you like a copy?","问要不要复印"]],
 "grammar":"Here are + 并列复数宾语（口语中 passport and ticket 连用时 are 常见，逐件也可 here's）；return ticket 固定『返程票』。",
 "pron":"连读：Here are my→/hɪr ɑr maɪ/（r 与 ɑ）；are my passport→/ɑr maɪ ˈpæspɔrt/；passport and→/ˈpæspɔrt ən/（t 失去）；and return→/ən rɪˈtɜrn/（n 与 r）；return ticket→/rɪˈtɜrn ˈtɪkɪt/（n 与 t）。弱读：and→/ən/。失去爆破：passport and /ˈpæspɔr(t) ən/。重音：return /rɪˈtɜrn/ 在后、ticket /ˈtɪkɪt/ 在前。"},
133: {"fullIpa":"/wɛr ʃʊd aɪ ɡoʊ θruː ˈkʌstəmz/",
 "variants":[["Which way is customs?","标牌式问路"],["Where's the customs hall?","问大厅位置"],["Nothing to declare or goods to declare, which line?","直接问通道"]],
 "scenes":[["落地后分流","Where should I go through customs?","指示 Follow the green channel if nothing to declare."],["绿色通道确认","Is the green line for nothing to declare?","确认规则"],["有物品申报","I have goods to declare, which channel?","走红色通道"]],
 "grammar":"go through customs 固定搭配『过海关』（through 表穿过流程）；customs 复数形式表单数意义。",
 "pron":"连读：Where should I→/wɛr ʃʊ daɪ/；should I go→/ʃʊ daɪ ɡoʊ/；go through→/ɡoʊ θruː/（oʊ 与 θ）；through customs→/θruː ˈkʌstəmz/（uː 与 k）。弱读：should→/ʃʊ/。重音：customs /ˈkʌstəmz/ 在前。失去爆破：无典型。"},
134: {"fullIpa":"/du aɪ hæv ˈɛniθɪŋ tə dɪˈklɛr naɪθɪŋ tə dɪˈklɛr/",
 "variants":[["Anything to declare?","问句最简"],["I have nothing to declare.","只说答句"],["Just my personal items.","自然口语答"]],
 "scenes":[["海关问旅客","Do you have anything to declare?","回答 Nothing to declare. / I have some cigarettes to declare."],["主动申报","I have goods to declare.","走红色通道"],["免税额度确认","How much wine can I bring in duty-free?","问限额"]],
 "grammar":"anything 用于疑问句（否定句用 nothing）；to declare 不定式作后置定语；declare 动词『申报』。",
 "pron":"连读：Do I have→/du aɪ hæv/；have anything→/hæv ˈɛniθɪŋ/（v 与 ɛ）；anything to→/ˈɛniθɪŋ tə/（ŋ 与 t）；to declare→/tə dɪˈklɛr/（t 与 d 只读一次）。弱读：to→/tə/；do→/də/。失去爆破：anything to /ˈɛniθɪŋ (t)ə/。重音：declare /dɪˈklɛr/ 在后。"},
135: {"fullIpa":"/kʊd ju tɛl mi wɛr ðə dɪˈpɑrtʃər ɡeɪt ɪz/",
 "variants":[["Where's the departure gate?","直接问句"],["Which gate for the Paris flight?","报航班问"],["How do I get to gate 22?","已知门号问路"]],
 "scenes":[["看不懂指示","Could you tell me where the departure gate is?","回 Gate 22, take the shuttle to Terminal 2."],["登机牌确认","What gate does it say on the boarding pass?","自查互查"],["改登机口","Has the gate changed?","屏幕核对"]],
 "grammar":"Could you tell me + where 从句（疑问句语序：where…is 不是 is…where）；departure gate 复合名词。",
 "pron":"同化：Could you→/kʊdʒu/（d+j→dʒ，关键！）。连读：tell me where→/tɛl mi wɛr/；me where the→/mi wɛr ðə/；where the departure→/wɛr ðə dɪˈpɑrtʃər/；departure gate is→/dɪˈpɑrtʃər ɡeɪt ɪz/（t 与 ɪ）。弱读：you→/jə/；the→/ðə/。失去爆破：gate is /ɡeɪ(t) ɪz/ 轻微。"},
136: {"fullIpa":"/hæz ˈbɔrdɪŋ ˈstɑrtɪd fɔr ɡeɪt ˈtwɛntiˈtuː/",
 "variants":[["Has boarding begun at gate 22?","begun 换 started"],["Are they boarding at gate 22 yet?","they 泛指"],["Is gate 22 boarding now?","口语最简"]],
 "scenes":[["到登机口","Has boarding started for gate twenty-two?","工作人员回 Not yet, in about twenty minutes."],["广播没听清","Did they call our gate yet?","问邻座"],["优先登机","Are priority passengers boarding first?","问顺序"]],
 "grammar":"Has + 过去分词 现在完成时问句；board 动词『登机』（boarding 动名词）；twenty-two 基数词作定语。",
 "pron":"连读：Has boarding→/hæz ˈbɔrdɪŋ/（z 与 b）；boarding started→/ˈbɔrdɪŋ ˈstɑrtɪd/（ŋ 与 s）；started for→/ˈstɑrtɪd fər/（d 与 f）；for gate→/fər ɡeɪt/（r 与 ɡ）；gate twenty-two→/ɡeɪt ˈtwɛntituː/（t 与 t 相邻只读一次）。弱读：for→/fər/。重音：twenty-two 重音在 two。"},
137: {"fullIpa":"/wʌt taɪm dʌz ˈbɔrdɪŋ bɪˈɡɪn/",
 "variants":[["When does boarding start?","when 通用"],["When do we start boarding?","we 亲切"],["What's the boarding time?","名词问法"]],
 "scenes":[["候机楼问","What time does boarding begin?","回 Usually forty minutes before departure."],["广播确认","They said boarding at nine twenty?","复述确认"],["赶时间","How long is full boarding?","问全程时长"]],
 "grammar":"What time 助动词 does + 主语 + 动词原形；begin/start 同义，begin 稍正式。",
 "pron":"连读：What time does→/wʌt taɪm dʌz/（t 与 t 相邻只读一次；m 与 d）；time does boarding→/taɪm dʌz ˈbɔrdɪŋ/（z 与 b）；does boarding begin→/dʌz ˈbɔrdɪŋ bɪˈɡɪn/（ŋ 与 b）。弱读：does→/dəz/。重音：begin /bɪˈɡɪn/ 在后。失去爆破：What time /wʌ(t) taɪm/。"},
138: {"fullIpa":"/ɪz ðɪs ðə raɪt laɪn fɔr ɡeɪt fɪfˈtin/",
 "variants":[["Is this the line for gate 15?","15 读 fifteen"],["Am I in the right line for gate fifteen?","in the right line 惯用"],["Does this queue go to gate fifteen?","queue 英式"]],
 "scenes":[["排队前确认","Is this the right line for gate fifteen?","工作人员回 Yes, this one. / No, that one over there."],["排错补救","Sorry, wrong line, excuse me.","挤出去"],["优先通道","Which line is for families?","带娃优先"]],
 "grammar":"the right + 名词『正确的…』（反义 the wrong line）；for gate + 数字 表目的；line/queue 都表队列（美/英）。",
 "pron":"连读：Is this the→/ɪz ðɪs ðə/（z 与 ð；s 与 ð）；the right line→/ðə raɪt laɪn/（t 与 l）；right line for→/raɪt laɪn fər/；line for gate→/laɪn fər ɡeɪt/（n 与 f）；gate fifteen→/ɡeɪt fɪfˈtin/（t 与 f）。弱读：for→/fər/；the→/ðə/。重音：fifteen /ˌfɪfˈtin/ 在后（注意与 fifty /ˈfɪfti/ 区分，关键！）。"},
139: {"fullIpa":"/kʊd ju kɔl ə ˈtæksi fɔr mi pliz/",
 "variants":[["Could you get me a taxi?","get 换 call"],["Can you call a cab for me?","cab 美式"],["I need a taxi, please.","直接表达需求"]],
 "scenes":[["酒店前台","Could you call a taxi for me, please?","前台回 Sure, five minutes. / The taxi rank is just outside."],["餐厅结账后","Could you call me a cab?","服务员代叫"],["代驾口语复用","Could you call me a ride?","网约车也通"]],
 "grammar":"call + 交通工具『叫/预约』；for me 介词短语表受益人；cab = taxi 美式口语。",
 "pron":"同化：Could you→/kʊdʒu/（d+j→dʒ，关键！）。连读：call a→/kɔl ə/（l 与 ə）；a taxi for→/ə ˈtæksi fər/；taxi for me→/ˈtæksi fər mi/（i 与 f；r 与 m）。弱读：you→/jə/；a→/ə/；for→/fər/。重音：taxi /ˈtæksi/ 在前。"},
140: {"fullIpa":"/ˈrʌfli haʊ mʌtʃ ɪz ɪt tu ðə ˈsɪti ˈsɛntər baɪ ˈtæksi/",
 "variants":[["About how much to downtown by taxi?","省略 is it"],["Roughly how much would a taxi cost?","would 委婉"],["How much is the fare to the city center?","fare 车费"]],
 "scenes":[["上车前问","Roughly how much is it to the city center by taxi?","司机回 Around thirty dollars, give or take."],["防绕路","What's the usual fare? I don't want surprises.","先立规矩"],["比较交通","Is it much cheaper by bus?","比价"]],
 "grammar":"Roughly 副词『大约』修饰整句（= about/approximately）；by + 交通方式『乘坐…』；the city center 市中心（美式 downtown）。",
 "pron":"连读：Roughly how much→/ˈrʌfli haʊ mʌtʃ/（i 与 h；w 与 m）；much is it→/mʌtʃ ɪz ɪt/（tʃ 与 ɪ）；is it to→/ɪz ɪt tə/（t 与 t 只读一次）；it to the→/ɪt tə ðə/；to the city→/tə ðə ˈsɪti/；by taxi→/baɪ ˈtæksi/（aɪ 与 t）。弱读：to→/tə/；the→/ðə/；is→/ɪz/。重音：roughly /ˈrʌfli/、center /ˈsɛntər/。"},
141: {"fullIpa":"/du ju teɪk ˈkrɛdɪt kɑrdz ɔr kæʃ ˈoʊnli/",
 "variants":[["Do you take cards?","极简"],["Card or cash?","口语二选一"],["Is cash the only option?","反向确认"]],
 "scenes":[["出租车/商店","Do you take credit cards or cash only?","回 Cards are fine. / Cash only, sorry."],["小摊","Can I scan the QR code?","问扫码支付"],["备用方案","Where's the nearest ATM?","只收现金时找取款机"]],
 "grammar":"take 动词『接受（支付方式）』；credit cards 复数泛指；or 连接选择疑问句。",
 "pron":"连读：Do you take→/du ju teɪk/（u 与 j）；you take credit→/ju teɪk ˈkrɛdɪt/（k 与 k 相邻只读一次轻擦）；credit cards or→/ˈkrɛdɪt kɑrdz ɔr/（t 与 k；z 与 ɔ）；or cash only→/ɔr kæʃ ˈoʊnli/（r 与 k）。弱读：do→/də/；you→/jə/；or→/ər/。失去爆破：take credit /teɪ(k) ˈkrɛdɪt/。缩读注意：or 弱读 /ər/。"},
142: {"fullIpa":"/kʊd ju ˈoʊpən ðə trʌŋk fɔr maɪ ˈlʌɡɪdʒ/",
 "variants":[["Could you pop the trunk?","pop 口语『打开』"],["Can you open the boot?","boot 英式后备箱"],["Trunk, please.","手势+短语"]],
 "scenes":[["上出租车","Could you open the trunk for my luggage?","司机按遥控开后备箱"],["放行李","Mind if I put my bags in the trunk?","先征得同意"],["取行李","I'll get my luggage from the trunk.","下车时说"]],
 "grammar":"trunk 美式『后备箱』（英式 boot）；for my luggage 表用途；open 及物动词。",
 "pron":"连读：Could you open→/kʊdʒu ˈoʊpən/（d+j 同化；ə 与 oʊ）；you open the→/ju ˈoʊpən ðə/；open the trunk→/ˈoʊpən ðə trʌŋk/（n 与 ð）；the trunk for→/ðə trʌŋk fər/；trunk for my→/trʌŋk fər maɪ/（k 与 f；r 与 m）。弱读：you→/jə/；the→/ðə/；for→/fər/。失去爆破：trunk for /trʌŋ(k) fər/。"},
143: {"fullIpa":"/pliz drɑp mi ˈɔf ət ðə meɪn ˈɛntrəns/",
 "variants":[["Please drop me at the main entrance.","省 off 也自然"],["Could you drop me off at the front door?","front door 换法"],["Main entrance, please.","极简报地点"]],
 "scenes":[["出租车报目的地","Please drop me off at the main entrance.","司机回 Got it, the big glass doors?"],["商场/景区","Drop me at the north entrance, please.","指定入口"],["临近修正","Actually, drop me at the corner instead.","临时改地点"]],
 "grammar":"drop sb. off 固定短语『让某人下车』（off 副词，宾语可插中间 drop me off / drop off me ×）；the main entrance 正门（还有 side entrance 侧门）。",
 "pron":"连读：drop me off→/drɑp mi ˈɔf/（p 与 m）；me off at→/mi ˈɔf ət/（f 与 ə）；off at the→/ɔf ət ðə/；at the main→/ət ðə meɪn/；the main entrance→/ðə meɪn ˈɛntrəns/（n 与 ɛ）。弱读：at→/ət/；the→/ðə/。失去爆破：drop me /drɑ(p) miː/。重音：entrance /ˈɛntrəns/ 在前。"},
144: {"fullIpa":"/kʊd ju sloʊ daʊn ə ˈlɪtəl pliz/",
 "variants":[["Could you slow down a bit?","bit 换 little"],["You're going a bit fast for me.","委婉陈述式"],["Please drive a little slower.","祈使句"]],
 "scenes":[["出租车上","Could you slow down a little, please?","司机回 Oh, sorry about that."],["山路骑行","Could you give us more space and slow down?","对车流喊话"],["新手安抚","Take it slow, please.","让司机稳着开"]],
 "grammar":"slow down 固定短语『减速』（反义 speed up）；a little 程度状语『一点』；委婉度 Could > Can。",
 "pron":"连读：Could you slow→/kʊdʒu sloʊ/（d+j 同化；u 与 s）；you slow down→/ju sloʊ daʊn/（oʊ 与 d）；slow down a→/sloʊ daʊn ə/；down a little→/daʊn ə ˈlɪtəl/（n 与 ə）；a little please→/ə ˈlɪtəl pliz/（l 与 p）。弱读：you→/jə/；a→/ə/。重音：little /ˈlɪtəl/ 在前、down /daʊn/ 单音节。"},
145: {"fullIpa":"/kip ðə tʃeɪndʒ θæŋk ju/",
 "variants":[["Keep the rest.","省 thank you"],["You can keep the change.","can 客气"],["That's for you.","给小费手势语"]],
 "scenes":[["付现金打车","Here's fifty. Keep the change, thank you.","司机回 Thank you very much!"],["小额找零","Don't worry about the change.","摆手示意"],["餐厅留零钱","The rest is for you.","桌上留小费"]],
 "grammar":"祈使句 Keep + 宾语『留着吧』；the change 不可数『找零』；介词短语省略（Keep the change for yourself 的省略）。",
 "pron":"连读：Keep the change→/kip ðə tʃeɪndʒ/（p 与 ð；ə 与 tʃ）；the change thank→/ðə tʃeɪndʒ θæŋk/（dʒ 与 θ）；change thank you→/tʃeɪndʒ θæŋk ju/（ŋ 与 j）。弱读：the→/ðə/；you→/jə/。重音：keep 单音节、change /tʃeɪndʒ/ 单音节，句重音在 change。"},
146: {"fullIpa":"/ɪz ðə ˈmiːtər ˈrʌnɪŋ/",
 "variants":[["Is the meter on?","on 换 running"],["Could you turn on the meter?","请求开启"],["Meter, please.","轻敲仪表示意"]],
 "scenes":[["上车起步","Is the meter running?","司机回 Yes, it's on. / Just started it."],["发现没打表","Could you use the meter, please?","要求按表计费"],["下车看表","How much does the meter say?","对表付钱"]],
 "grammar":"meter 名词『计价器』；run 动词『（机器）运转』（Is the meter running = 开着吗）；进行时表状态。",
 "pron":"连读：Is the meter→/ɪz ðə ˈmiːtər/（z 与 ð；ə 与 m）；the meter running→/ðə ˈmiːtər ˈrʌnɪŋ/（r 与 r 相连加滑音 /ˈmiːtə rˈrʌnɪŋ/）。弱读：the→/ðə/。重音：meter /ˈmiːtər/ 在前、running /ˈrʌnɪŋ/ 在前。闪音：meter 美式 /ˈmiːɾɚ/（t 闪音，关键！）。"},
147: {"fullIpa":"/wɪtʃ ˈsʌbweɪ laɪn ɡoʊz tu ðə mjuˈziəm/",
 "variants":[["Which line goes to the museum?","省 subway 语境明"],["Which metro line is the museum on?","be on 换法"],["How do I get to the museum by subway?","how 问路线"]],
 "scenes":[["地铁问路","Which subway line goes to the museum?","回 Line 2, then change to Line 4 at Central."],["站内看图","Is this the right platform for Line 2?","站台上再确认"],["票务窗口","One ticket to the museum station, please.","顺便买票"]],
 "grammar":"which + 单数名词选择疑问句；go to 表『通往/到达』；subway line 地铁线路。",
 "pron":"连读：Which subway line→/wɪtʃ ˈsʌbweɪ laɪn/（tʃ 与 s；eɪ 与 l）；line goes to→/laɪn ɡoʊz tə/（n 与 ɡ；z 与 t）；goes to the→/ɡoʊz tə ðə/；to the museum→/tə ðə mjuˈziəm/。弱读：to→/tə/；the→/ðə/。重音：museum /mjuˈziəm/ 在中后部（三音节）。"},
148: {"fullIpa":"/aɪd laɪk ə ˈsɪŋɡəl ˈtɪkɪt tu ˈsɛntrəl ˈsteɪʃən/",
 "variants":[["One single to Central Station, please.","极简购票"],["A one-way ticket to Central Station, please.","one-way 美式"],["Return to Central, please.","反向：买往返"]],
 "scenes":[["售票窗口","I'd like a single ticket to Central Station, please.","售票员回 That's two fifty."],["自动售票机","Which option is a single?","界面求助"],["选票种","Single or return? — Single, please.","被反问时回答"]],
 "grammar":"single ticket 英式『单程票』（美式 one-way，往返 return / round-trip）；a + 数量 + 票；to + 站名表目的地。",
 "pron":"缩读：I'd = I would /aɪd/。连读：I'd like a→/aɪd laɪk ə/；like a single→/laɪk ə ˈsɪŋɡəl/（k 与 ə；ə 与 s）；a single ticket→/ə ˈsɪŋɡəl ˈtɪkɪt/（l 与 t）；ticket to Central→/ˈtɪkɪt tu ˈsɛntrəl/（t 与 t 只读一次；t 与 s）；Central Station→/ˈsɛntrəl ˈsteɪʃən/（l 与 s）。弱读：a→/ə/；to→/tə/。"},
149: {"fullIpa":"/ɪz ə deɪ pæs wɜrθ ɪt fɔr ˈɡɛtɪŋ əˈraʊnd/",
 "variants":[["Is a day pass worth it?","省目的状语"],["Would a day pass save me money?","save 换角度"],["Should I just get single tickets instead?","反向比较"]],
 "scenes":[["票务咨询","Is a day pass worth it for getting around?","工作人员回 If you take more than three rides, yes."],["算账决策","How many rides to break even?","问回本次数"],["多人同行","Is there a group day pass?","问团体票"]],
 "grammar":"be worth it 固定搭配『值得（花这个钱）』；动名词短语 for getting around 表用途（get around 固定短语『四处走动/出行』）。",
 "pron":"连读：Is a day pass→/ɪz ə deɪ pæs/（z 与 ə；eɪ 与 p）；day pass worth→/deɪ pæs wɜrθ/（s 与 w）；pass worth it→/pæs wɜrθ ɪt/（θ 与 ɪ）；worth it for→/wɜrθ ɪt fər/（t 与 f）；it for getting→/ɪt fər ˈɡɛtɪŋ/（r 与 ɡ）；getting around→/ˈɡɛtɪŋ əˈraʊnd/（ŋ 与 ə）。弱读：a→/ə/；for→/fər/。失去爆破：worth it /wɜrθ ɪt/ 常并作 /wɜr θɪt/。"},
150: {"fullIpa":"/dʌz ðɪs treɪn stɑp ət ˈɛvri ˈsteɪʃən/",
 "variants":[["Is this a stopping train?","英式 stopping train"],["Does this train stop at all stations?","all 强调全部"],["Is this an express?","反向问快车"]],
 "scenes":[["站台确认","Does this train stop at every station?","回 No, this is an express. / Yes, all stops."],["怕坐过站","Does it stop at Riverside?","只问关键站"],["换乘规划","If it skips my station I'll take the next one.","制定备选"]],
 "grammar":"Does + 主语 + 动词原形；stop at + 站名『停靠某站』；every station 每一站（express 表『快车』反义）。",
 "pron":"连读：Does this train→/dʌz ðɪs treɪn/（z 与 ð；s 与 t）；this train stop→/ðɪs treɪn stɑp/（n 与 s）；train stop at→/treɪn stɑp ət/（p 与 ə）；stop at every→/stɑp ət ˈɛvri/（t 失去）；at every station→/ət ˈɛvri ˈsteɪʃən/（i 与 s）。弱读：does→/dəz/；at→/ət/。失去爆破：stop at /stɑ(p) ət/。重音：station /ˈsteɪʃən/ 在前。"},
}
