# -*- coding: utf-8 -*-
# 语料池 5/5：日常 · 表达/时间/社交/情绪/处事（接续池4）
RAW = [
"Just a moment, let me check my schedule.|稍等，我看下日程。|daily|时间/安排|short|schedule|/ˈskɛdʒuːl/|n.日程",
"Time flies when you're having fun.|开心的时候时间过得飞快。|daily|时间/感叹|short|fly|/flaɪ/|v.飞逝",
"It's a quarter past seven now.|现在是七点一刻。|daily|时间/报时|short|quarter|/ˈkwɔrtər/|n.一刻钟",
"The meeting got pushed back to four o'clock.|会议推迟到四点了。|daily|时间/改期|short|push back|/pʊʃ bæk/|phr.推迟",
"I'll be ready in about ten minutes.|我大概十分钟后就好。|daily|时间/等待|short|ready|/ˈrɛdi/|adj.准备好的",
"Let's meet at half past six instead.|改六点半见吧。|daily|时间/约定|short|half past|/hæf pæst/|phr.几点半",
"How many people are coming to the party?|派对大概来多少人？|daily|数量/询问|short|how many|/haʊ ˈmɛni/|phr.多少",
"There are plenty of seats left in the back.|后面还有很多空位。|daily|数量/描述|short|plenty|/ˈplɛni/|n.大量",
"A couple of friends are coming over tonight.|今晚有几个朋友要来。|daily|数量/描述|short|a couple of|/ə ˈkʌpəl əv/|phr.两三个",
"I need a bit more time to think it over.|我需要再多一点时间考虑。|daily|数量/程度|long|a bit|/ə bɪt/|phr.一点",
"Could I have a little more sugar in my coffee?|咖啡里能再多加点糖吗？|daily|数量/要求|long|a little|/ə ˈlɪtəl/|phr.少量",
"That's way too much food for two people.|两个人这菜也太多了。|daily|数量/评价|short|way too much|/weɪ tu mʌtʃ/|phr.太多了",
"I bought this online at half price.|这是我网上半价买的。|daily|购物/网购|short|half price|/hæf praɪs/|phr.半价",
"The package should arrive in two or three days.|包裹大概两三天到。|daily|购物/快递|short|package|/ˈpækɪdʒ/|n.包裹",
"Could I change the delivery address, please?|能改一下收货地址吗？|daily|购物/快递|long|delivery address|/dɪˈlɪvəri əˈdrɛs/|phr.收货地址",
"I want to return this item I bought last week.|我想退上周买的这件东西。|daily|购物/退换|long|item|/ˈaɪtəm/|n.物品",
"Is this product in stock right now?|这个商品现在有货吗？|daily|购物/库存|short|in stock|/ɪn stɑk/|phr.有现货",
"Can I pick it up at the store instead of waiting for delivery?|我能去店里自提而不用等快递吗？|daily|购物/自提|long|pick up|/pɪk ʌp/|phr.自提",
"The checkout line at that supermarket moves fast.|那家超市结账队伍走得挺快。|daily|购物/体验|long|checkout|/ˈtʃɛkaʊt/|n.结账",
"I love what you've done with this place!|你把这里布置得真好！|daily|社交/夸赞|short|do with|/du wɪð/|phr.布置处理",
"You have great taste in music.|你音乐品味真好。|daily|社交/夸赞|short|taste|/teɪst/|n.品味",
"That's a lovely shirt you're wearing.|你这件衬衫真好看。|daily|社交/夸赞|short|lovely|/ˈlʌvli/|adj.好看的",
"How did your presentation go yesterday?|你昨天的展示怎么样？|daily|社交/关心|short|presentation|/ˌprɛzənˈteɪʃən/|n.展示汇报",
"I heard you moved to a new apartment, how is it?|听说你搬了新公寓，怎么样？|daily|社交/近况|long|apartment|/əˈpɑrtmənt/|n.公寓",
"We should hang out more often like this.|我们应该经常这样出来聚聚。|daily|社交/邀约|short|more often|/mɔr ˈɔfən/|phr.更经常",
"It was so nice talking with you today.|今天和你聊得真开心。|daily|社交/道别|short|nice|/naɪs/|adj.愉快的",
"Sorry, I have to take this call.|抱歉，我得接个电话。|daily|社交/离席|short|take this call|/teɪk ðɪs kɔl/|phr.接电话",
"Go ahead, I'll catch up with you later.|你先忙，我回头找你。|daily|社交/告别|short|catch up|/kætʃ ʌp/|phr.跟上",
"Guess what? I finally got my driver's license!|你猜怎么着？我驾照终于拿到了！|daily|情绪/激动|long|driver's license|/ˈdraɪvərz ˈlaɪsəns/|phr.驾照",
"You're kidding! When did that happen?|不是吧！什么时候的事？|daily|情绪/惊讶|short|kid|/kɪd/|v.开玩笑",
"No way, that's incredible!|不会吧，太不可思议了！|daily|情绪/惊讶|short|no way|/noʊ weɪ/|phr.不可能",
"What a small world to meet you here!|在这儿遇见你，世界真小！|daily|情绪/惊讶|short|small world|/smɔl wɜrld/|phr.世界真小",
"I can't believe my eyes right now.|我简直不敢相信自己的眼睛。|daily|情绪/惊讶|short|believe|/bɪˈliːv/|v.相信",
"That's so thoughtful of you.|你真是太贴心了。|daily|情绪/感动|short|thoughtful|/ˈθɔtfəl/|adj.体贴的",
"I really appreciate what you've done for me.|我真的很感激你为我做的。|daily|情绪/感激|long|appreciate|/əˈpriːʃieɪt/|v.感激",
"Words can't describe how happy I am.|言语无法形容我有多开心。|daily|情绪/高兴|short|describe|/dɪˈskraɪb/|v.描述",
"I felt a bit down yesterday, but I'm better now.|我昨天有点低落，不过现在好多了。|daily|情绪/低落|long|down|/daʊn/|adj.情绪低落",
"It broke my heart to see her cry.|看到她哭我心都碎了。|daily|情绪/难过|short|break one's heart|/breɪk wʌnz hɑrt/|phr.心碎",
"I'm so proud of what we achieved together.|我为我们共同取得的成就骄傲。|daily|情绪/自豪|long|achieve|/əˈtʃiːv/|v.实现",
"To be frank, I wasn't expecting much.|坦白说，我本来没抱太大期望。|daily|表达/坦率|short|to be frank|/tu bi fræŋk/|phr.坦白说",
"Honestly speaking, it's not my cup of tea.|说实话，这不太合我口味。|daily|表达/偏好|long|not my cup of tea|/nɑt maɪ kʌp əv tiː/|phr.不合喜好",
"As far as I know, the shop closes early on Sundays.|据我所知，那家店周日关门早。|daily|表达/观点|long|as far as|/æz fɑr æz/|phr.就…而言",
"If I'm honest, I forgot all about it.|老实说，我完全忘了这茬。|daily|表达/坦白|long|honest|/ˈɑnɪst/|adj.诚实的",
"In my opinion, the first option is better.|依我看，第一个选项更好。|daily|表达/观点|short|in my opinion|/ɪn maɪ əˈpɪnjən/|phr.依我看",
"To sum up, we need more time and information.|总之，我们需要更多时间和信息。|daily|表达/总结|long|to sum up|/tu sʌm ʌp/|phr.总而言之",
"For what it's worth, I think you did great.|不管有没有用，我觉得你做得很棒。|daily|表达/安慰|long|for what it's worth|/fɔr wʌts ɪts wɜrθ/|phr.无论如何",
"Long story short, we missed the last train.|长话短说，我们错过末班车了。|daily|表达/简述|long|long story short|/lɔŋ ˈstɔri ʃɔrt/|phr.长话短说",
"In a nutshell, the plan didn't work out.|简而言之，计划没成。|daily|表达/简述|short|in a nutshell|/ɪn ə ˈnʌtʃɛl/|phr.简而言之",
"On second thought, let's just stay home.|再想想，我们还是宅家吧。|daily|表达/改变主意|long|on second thought|/ɑn ˈsɛkənd θɔt/|phr.转念一想",
"Come to think of it, I did see him earlier.|这么一想，我早些时候确实见过他。|daily|表达/回忆|long|come to think of it|/kʌm tu θɪŋk əv ɪt/|phr.想起来了",
"Now that you mention it, something does feel off.|你这么一说，确实感觉有点不对。|daily|表达/呼应|long|off|/ɔf/|adj.不对劲的",
"That reminds me, I need to buy a birthday gift.|这倒提醒我了，我得买个生日礼物。|daily|表达/联想|long|remind|/rɪˈmaɪnd/|v.提醒",
"By the way, is the shop open on holidays?|对了，那家店节假日营业吗？|daily|表达/补充|short|by the way|/baɪ ðə weɪ/|phr.顺便说",
"Speaking of food, have you tried that new place?|说到吃的，你去试过那家新店吗？|daily|表达/联想|long|speaking of|/ˈspiːkɪŋ əv/|phr.说到",
"Anyway, let's not get into that now.|总之，咱们现在先不谈这个。|daily|表达/转移|short|anyway|/ˈɛniweɪ/|adv.总之",
"To be fair, both sides have valid points.|平心而论，双方都有道理。|daily|表达/客观|long|valid|/ˈvælɪd/|adj.有道理的",
"I was on the verge of giving up, honestly.|说实话，我差点就放弃了。|daily|表达/经历|long|on the verge of|/ɑn ðə vɜrdʒ əv/|phr.濒于",
"It turned out better than I expected.|结果比我预期的好。|daily|表达/结果|short|turn out|/tɜrn aʊt/|phr.结果是",
"I ended up buying two pairs of shoes.|我最后买了两双鞋。|daily|表达/结果|short|end up|/ɛnd ʌp/|phr.最终",
"It's not as difficult as it looks.|它没有看上去那么难。|daily|表达/评价|short|as...as|/æz æz/|phr.像…一样",
"I'd rather stay home than go out tonight.|今晚我宁愿待家里也不想出门。|daily|表达/偏好|long|would rather|/wʊd ˈræðər/|phr.宁愿",
"I prefer walking when the weather is nice.|天气好的时候我更喜欢走路。|daily|表达/偏好|long|prefer|/prɪˈfɜːr/|v.更喜欢",
"There's nothing better than a hot shower after work.|下班后没比冲个热水澡更爽的了。|daily|表达/感受|long|nothing better|/ˈnʌθɪŋ ˈbɛtər/|phr.没有更好的",
"It takes two to tango, you know.|你知道的，一个巴掌拍不响。|daily|表达/俗语|short|tango|/ˈtæŋɡoʊ/|n.探戈",
"Better late than never, right?|迟做总比不做好，对吧？|daily|表达/俗语|short|better late than never|/ˈbɛtər leɪt ðən ˈnɛvər/|phr.迟做比不做好",
"Practice what you preach before you say that.|先以身作则再说这话吧。|daily|表达/俗语|long|preach|/priːtʃ/|v.说教",
"Easier said than done, my friend.|说来容易做来难，朋友。|daily|表达/俗语|short|easier said than done|/ˈiːziər sɛd ðən dʌn/|phr.说来容易做来难",
"Don't judge a book by its cover.|别以貌取人。|daily|表达/俗语|short|judge|/dʒʌdʒ/|v.评判",
"When in Rome, do as the Romans do.|入乡随俗嘛。|daily|表达/俗语|long|when in Rome|/wɛn ɪn roʊm/|phr.入乡随俗",
"Actions speak louder than words.|行动胜于言语。|daily|表达/俗语|long|action|/ˈækʃən/|n.行动",
"Every cloud has a silver lining.|天无绝人之路。|daily|表达/俗语|long|silver lining|/ˈsɪlvər ˈlaɪnɪŋ/|phr.一线希望",
"The early bird catches the worm, as they say.|早起的鸟儿有虫吃，常言道。|daily|表达/俗语|long|early bird|/ˈɜrli bɜrd/|phr.早起者",
"Let me think about it for a while.|让我想一会儿。|daily|犹豫/思考|short|for a while|/fər ə waɪl/|phr.一会儿",
"That's a good question, actually.|这问题问得好，说实话。|daily|回应/思考|short|actually|/ˈæktʃuəli/|adv.实际上",
"I'm not quite sure how to answer that.|我还不太确定该怎么回答。|daily|犹豫/不确定|short|not quite sure|/nɑt kwaɪt ʃʊr/|phr.不太确定",
"Give me a second to think this through.|给我点时间想清楚。|daily|犹豫/思考|short|think through|/θɪŋk θruː/|phr.想透彻",
"Off the top of my head, I'd say about fifty.|不假思索的话，我猜大概五十。|daily|表达/估计|long|off the top of one's head|/ɔf ðə tɑp əv wʌnz hɛd/|phr.不假思索",
"It's a tough call between the two options.|这两个选项之间很难抉择。|daily|犹豫/抉择|short|tough call|/tʌf kɔl/|phr.艰难决定",
"I keep going back and forth on this decision.|这个决定我一直摇摆不定。|daily|犹豫/反复|long|back and forth|/bæk ənd fɔrθ/|phr.来回反复",
"Whatever floats your boat, honestly.|你喜欢就好，说真的。|daily|回应/随和|short|float|/floʊt/|v.漂浮",
"Suit yourself, but don't say I didn't warn you.|随你，但别怪我没提醒你。|daily|回应/提醒|long|suit yourself|/sut jʊrˈsɛlf/|phr.随你便",
"Fine by me, either way works.|我没意见，怎么都行。|daily|回应/同意|short|fine|/faɪn/|adj.可以的",
"It doesn't matter to me at all.|我完全无所谓。|daily|回应/中立|short|matter|/ˈmætər/|v.要紧",
"Now you're talking!|这才对嘛！|daily|回应/赞同|short|now you're talking|/naʊ jʊr ˈtɔkɪŋ/|phr.这才像话",
"You read my mind completely.|你完全猜中了我的想法。|daily|回应/默契|short|read one's mind|/rid wʌnz maɪnd/|phr.看穿心思",
"Tell me about it, it happens every time.|可不是嘛，每次都这样。|daily|回应/共鸣|short|tell me about it|/tɛl mi əˈbaʊt ɪt/|phr.可不是嘛",
"I know exactly how you feel.|我完全懂你的感受。|daily|回应/共情|short|exactly|/ɪɡˈzæktli/|adv.完全地",
"That must have been really hard on you.|那对你来说一定很难。|daily|回应/共情|long|hard on|/hɑrd ɑn/|phr.对…苛刻",
"Chin up, better days are coming.|振作起来，好日子在后头。|daily|安慰/鼓励|short|chin up|/tʃɪn ʌp/|phr.别气馁",
"Tomorrow is another day, after all.|毕竟明天又是新的一天。|daily|安慰/宽慰|short|after all|/ˈæftər ɔl/|phr.毕竟",
"This too shall pass, trust me.|这也会过去的，相信我。|daily|安慰/宽慰|short|pass|/pæs/|v.过去",
]
