# -*- coding: utf-8 -*-
# 语料池 3/5：日常 · 寒暄/邀约/请求/意见（接续池2）
RAW = [
"Long time no see, how have you been?|好久不见，最近怎么样？|daily|寒暄/重逢|short|long time no see|/lɔŋ taɪm noʊ siː/|phr.好久不见",
"It's so good to run into you here!|在这儿碰到你真是太巧了！|daily|寒暄/偶遇|short|run into|/rʌn ˈɪntuː/|phr.偶遇",
"How's everything going with you lately?|你最近一切都好吗？|daily|寒暄/近况|short|lately|/ˈleɪtli/|adv.近来",
"What have you been up to these days?|你这些日子都在忙什么？|daily|寒暄/近况|short|up to|/ʌp tuː/|phr.忙于",
"Same as usual, just keeping busy.|老样子，就是忙。|daily|寒暄/回应|short|as usual|/əz ˈjuːʒuəl/|phr.像往常一样",
"Not bad, can't complain.|还行，没什么可抱怨的。|daily|寒暄/回应|short|complain|/kəmˈpleɪn/|v.抱怨",
"Take care of yourself, okay?|照顾好自己，好吗？|daily|告别/叮嘱|short|take care|/teɪk kɛr/|phr.保重",
"Let's catch up properly soon.|我们改天好好聚聚。|daily|告别/约定|short|catch up|/kætʃ ʌp/|phr.叙旧",
"Say hi to your family for me.|替我向你家人问好。|daily|告别/问候|short|say hi|/seɪ haɪ/|phr.问好",
"Have a safe trip back home.|回家路上注意安全。|daily|告别/祝福|short|safe|/seɪf/|adj.安全的",
"Let me walk you to the door.|我送你到门口。|daily|告别/送别|short|walk|/wɔːk/|v.陪…走",
"Let me introduce myself, I'm Li Ming from Chengdu.|自我介绍一下，我是来自成都的李明。|daily|社交/自我介绍|long|introduce|/ˌɪntrəˈduːs/|v.介绍",
"Here's my contact card with my number on it.|这是我的名片，上面有电话。|daily|社交/联系方式|long|contact|/ˈkɑntækt/|n.联系方式",
"Are you on WeChat? Let's add each other.|你用微信吗？我们加个好友吧。|daily|社交/加好友|short|add|/æd/|v.添加",
"I didn't quite catch your name just now.|我刚才没太记住你的名字。|daily|社交/问名|short|catch|/kætʃ/|v.听清",
"Sorry, what was your name again?|抱歉，能再说一遍你的名字吗？|daily|社交/问名|short|again|/əˈɡɛn/|adv.再一次",
"So what do you do for a living?|你是做什么工作的？|daily|社交/职业|short|for a living|/fər ə ˈlɪvɪŋ/|phr.谋生",
"How long have you been living here?|你在这儿住多久了？|daily|社交/居住|short|living|/ˈlɪvɪŋ/|v.居住(现在分词)",
"Do you come here often?|你常来这儿吗？|daily|社交/闲聊|short|often|/ˈɔːfən/|adv.经常",
"What time works best for you tomorrow?|明天你什么时间方便？|daily|时间/安排|short|work|/wɜːrk/|v.行得通",
"Let's say six thirty at the usual place.|那就六点半老地方见。|daily|时间/约定|short|usual|/ˈjuːʒuəl/|adj.平常的",
"I'm running a bit late, save me a seat.|我要迟到一会儿，帮我占个座。|daily|时间/迟到|short|run late|/rʌn leɪt/|phr.迟到",
"Shall we meet up around noon for lunch?|咱们中午一起吃个午饭怎么样？|daily|邀约/吃饭|long|meet up|/miːt ʌp/|phr.碰面",
"Are you free this coming weekend?|这个周末你有空吗？|daily|邀约/周末|short|free|/friː/|adj.有空的",
"Do you want to join us for dinner on Friday?|周五想和我们一起吃晚饭吗？|daily|邀约/吃饭|long|join|/dʒɔɪn/|v.加入",
"How about going hiking this Saturday?|这周六去爬山怎么样？|daily|邀约/运动|short|hiking|/ˈhaɪkɪŋ/|n.徒步",
"I'd love to, but I've already made plans.|我很想去，但已经有安排了。|daily|邀约/婉拒|long|made plans|/meɪd plænz/|phr.有安排了",
"Maybe some other time, I'm swamped this week.|这周忙疯了，改天吧。|daily|邀约/婉拒|long|swamped|/swɑmpt/|adj.忙得不可开交",
"Can we make it Sunday instead of Saturday?|能把周六改到周日吗？|daily|邀约/改期|short|instead of|/ɪnˈstɛd əv/|phr.而不是",
"Rain check? I have to work overtime tonight.|改天行吗？今晚得加班。|daily|邀约/改期|long|rain check|/reɪn tʃɛk/|phr.改天",
"Count me in for the karaoke night.|唱歌那场算我一个。|daily|邀约/答应|short|count in|/kaʊnt ɪn/|phr.把…算入",
"I'll let you know by Friday whether I can come.|周五之前我告诉你能不能来。|daily|邀约/待定|long|let know|/lɛt noʊ/|phr.告知",
"Would you like to come over for tea sometime?|有空来我家喝杯茶吗？|daily|邀约/做客|long|come over|/kʌm ˈoʊvər/|phr.来访",
"Could you do me a favor and close the window?|能帮我个忙把窗户关上吗？|daily|请求/帮忙|short|favor|/ˈfeɪvər/|n.帮忙",
"Would you mind giving me a hand with these boxes?|能帮我搬一下这些箱子吗？|daily|请求/帮忙|long|give a hand|/ɡɪv ə hænd/|phr.搭把手",
"Could you keep an eye on my dog this afternoon?|今天下午能帮我照看一下狗吗？|daily|请求/照看|long|afternoon|/ˌæftərˈnuːn/|n.下午",
"Sure, no problem at all.|当然，完全没问题。|daily|答应/爽快|short|no problem|/noʊ ˈprɑbləm/|phr.没问题",
"Sorry, I'm afraid I can't right now.|抱歉，我现在恐怕不行。|daily|请求/婉拒|short|afraid|/əˈfreɪd/|adj.恐怕",
"Is it okay if I open the window a bit?|我把窗户开一点可以吗？|daily|请求/许可|short|okay|/oʊˈkeɪ/|adj.可以的",
"Do you mind if I sit here?|你介意我坐这儿吗？|daily|请求/许可|short|mind|/maɪnd/|v.介意",
"May I borrow your pen for a second?|能借用一下你的笔吗？|daily|请求/借用|short|borrow|/ˈbɑroʊ/|v.借入",
"Could you repeat the address for me?|能再重复一遍地址吗？|daily|请求/重复|short|repeat|/rɪˈpiːt/|v.重复",
"Would you mind speaking up a little?|能大点声说吗？|daily|请求/音量|short|speak up|/spiːk ʌp/|phr.大声说",
"Can you help me figure out this form?|能帮我看看这个表怎么填吗？|daily|请求/帮忙|long|figure out|/ˈfɪɡjər aʊt/|phr.弄明白",
"Absolutely, I agree with you on that.|完全同意，这点我跟你看法一致。|daily|意见/赞同|short|agree with|/əˈɡriː wɪð/|phr.同意",
"That makes a lot of sense to me.|我觉得这很有道理。|daily|意见/赞同|short|make sense|/meɪk sɛns/|phr.有道理",
"I see your point, but I'm not so sure.|我明白你的意思，但我不太确定。|daily|意见/保留|long|point|/pɔɪnt/|n.观点",
"That's exactly what I was thinking.|这正是我所想的。|daily|意见/赞同|short|exactly|/ɪɡˈzæktli/|adv.正是",
 "I am afraid I see it differently.|恐怕我的看法不太一样。|daily|意见/分歧|short|differently|/ˈdɪfərəntli/|adv.不同地",
"Let's agree to disagree on this one.|这点我们各自保留意见吧。|daily|意见/分歧|long|agree to disagree|/əˈɡriː tuː ˌdɪsəˈɡriː/|phr.保留各自意见",
"Fair enough, I hadn't thought of that.|有道理，我之前没想到这点。|daily|意见/认同|short|fair enough|/fɛr ɪˈnʌf/|phr.说得有理",
"I'm still on the fence about it.|我还没拿定主意。|daily|意见/犹豫|short|on the fence|/ɑn ðə fɛns/|phr.犹豫不决",
"Let me sleep on it and get back to you.|让我考虑一晚再答复你。|daily|意见/拖延|long|sleep on it|/sliːp ɑn ɪt/|phr.考虑一晚",
"It's totally up to you.|完全由你决定。|daily|意见/放手|short|up to|/ʌp tuː/|phr.取决于",
"You have a point there.|你说的有道理。|daily|意见/认可|short|have a point|/hæv ə pɔɪnt/|phr.有道理",
"To be honest, I have mixed feelings about it.|说实话，我心情有点复杂。|daily|情绪/复杂|long|mixed feelings|/mɪkst ˈfiːlɪŋz/|phr.百感交集",
"I'm over the moon about the news.|听到这个消息我太高兴了。|daily|情绪/高兴|short|over the moon|/ˈoʊvər ðə muːn/|phr.欣喜若狂",
"That's such a relief to hear.|听到这就放心了。|daily|情绪/宽慰|short|relief|/rɪˈliːf/|n.宽慰",
"I'm a bit nervous about tomorrow's interview.|明天的面试我有点紧张。|daily|情绪/紧张|long|nervous|/ˈnɜːrvəs/|adj.紧张的",
"It really gets on my nerves.|这事真让我心烦。|daily|情绪/烦躁|short|get on one's nerves|/ɡɛt ɑn wʌnz nɜːrvz/|phr.让人心烦",
"I'm in a really good mood today.|我今天心情特别好。|daily|情绪/心情|short|mood|/muːd/|n.心情",
"Don't let it get you down.|别让这事影响你。|daily|安慰/鼓励|short|get down|/ɡɛt daʊn/|phr.使沮丧",
"Everything's going to be fine, you'll see.|一切都会好起来的，相信我。|daily|安慰/宽慰|short|fine|/faɪn/|adj.好的",
"I'm here for you if you need to talk.|想找人聊聊的话我随时都在。|daily|安慰/陪伴|long|here for you|/hɪr fər juː/|phr.支持你",
"Cheer up, things could be worse.|振作点，情况本可能更糟。|daily|安慰/鼓励|short|cheer up|/tʃɪr ʌp/|phr.振作",
"You've come so far, be proud of yourself.|你已经走了这么远，为自己骄傲吧。|daily|鼓励/肯定|long|be proud of|/bi praʊd əv/|phr.为…骄傲",
"Keep it up, you're doing great.|继续保持，你做得很棒。|daily|鼓励/肯定|short|keep it up|/kip ɪt ʌp/|phr.保持",
"Give it your best shot and see what happens.|尽力一试，看看结果如何。|daily|鼓励/尝试|long|best shot|/bɛst ʃɑt/|phr.全力一试",
"I'm terribly sorry for being late again.|再次迟到真是非常抱歉。|daily|道歉/迟到|short|terribly|/ˈtɛrəbli/|adv.非常",
"It's my fault entirely, I apologize.|这完全是我的错，我道歉。|daily|道歉/认错|short|entirely|/ɪnˈtaɪərli/|adv.完全地",
"Sorry to keep you waiting so long.|抱歉让你久等了。|daily|道歉/等待|short|keep waiting|/kip ˈweɪtɪŋ/|phr.让…等待",
"Please accept my sincere apologies.|请接受我诚挚的歉意。|daily|道歉/正式|short|sincere|/sɪnˈsɪr/|adj.诚挚的",
"No worries, it happens to everyone.|没事，谁都会遇到这种事。|daily|道歉/回应|short|no worries|/noʊ ˈwʌriz/|phr.别担心",
"That's quite all right, don't worry about it.|没关系的，别放在心上。|daily|道歉/回应|short|all right|/ɔl raɪt/|phr.没关系",
"I can't thank you enough for your help.|真是太感谢你的帮助了。|daily|感谢/表达|short|can't thank enough|/kænt θæŋk ɪˈnʌf/|phr.感激不尽",
"Thanks a million for the lovely gift.|万分感谢这个可爱的礼物。|daily|感谢/礼物|short|a million|/ə ˈmɪljən/|phr.万分",
"It's very kind of you to say that.|你这么说真是太客气了。|daily|感谢/回应|short|kind|/kaɪnd/|adj.好心的",
"Don't mention it, happy to help.|别客气，很乐意帮忙。|daily|感谢/回应|short|mention|/ˈmɛnʃən/|v.提及",
"My pleasure, anytime.|我的荣幸，随时效劳。|daily|感谢/回应|short|pleasure|/ˈplɛʒər/|n.荣幸",
"Hello, this is Wang speaking.|你好，我是王。|daily|电话/接听|short|speaking|/ˈspiːkɪŋ/|v.通话中",
"Could I speak to Mr. Zhang, please?|请问张先生在吗？|daily|电话/找人|short|speak to|/spiːk tuː/|phr.找…接电话",
"I'm calling about the appointment tomorrow.|我打电话是想说明天预约的事。|daily|电话/来电|long|appointment|/əˈpɔɪntmənt/|n.预约",
"Would you like to leave a message?|您要留言吗？|daily|电话/留言|short|message|/ˈmɛsɪdʒ/|n.留言",
"Could you ask him to call me back?|能让他给我回个电话吗？|daily|电话/回电|short|call back|/kɔl bæk/|phr.回电",
"I'm afraid you have the wrong number.|恐怕您打错电话了。|daily|电话/打错|short|wrong number|/rɔŋ ˈnʌmbər/|phr.打错电话",
"The line is terrible, could you call me back?|信号太差了，能打回来吗？|daily|电话/信号|long|line|/laɪn/|n.电话线路",
"I'll text you the details in a minute.|我一会儿把详情发消息给你。|daily|消息/发送|short|text|/tɛkst/|v.发短信",
"Did you get my message this morning?|你收到我今早的消息了吗？|daily|消息/确认|short|get|/ɡɛt/|v.收到",
"Just checking in to see how you're doing.|就是问候一下你近况如何。|daily|消息/问候|short|check in|/tʃɛk ɪn/|phr.问候",
"Sorry for the late reply, I've been busy.|抱歉回晚了，最近有点忙。|daily|消息/回复|long|reply|/rɪˈplaɪ/|n.回复",
"I'll keep you posted on any updates.|有新消息我会随时告诉你。|daily|消息/通知|long|keep posted|/kip ˈpoʊstɪd/|phr.随时告知",
]
