# -*- coding: utf-8 -*-
# 语料池 4/5：日常 · 家务/工作/学习/健康/建议（接续池3）
RAW = [
"Could you take out the trash when you leave?|你走的时候能顺手把垃圾带下去吗？|daily|家务/倒垃圾|long|trash|/træʃ/|n.垃圾",
"I'll do the dishes if you dry them.|你擦干我洗碗，行不？|daily|家务/分工|short|dishes|/ˈdɪʃɪz/|n.碗碟",
"The laundry needs doing before Friday.|周五之前得洗衣服。|daily|家务/洗衣|short|laundry|/ˈlɔndri/|n.待洗衣物",
"Could you hang the clothes out to dry?|能把衣服晾出去吗？|daily|家务/晾晒|short|hang out|/hæŋ aʊt/|phr.晾晒",
"Who's on cleaning duty this week?|这周谁值日打扫？|daily|家务/值日|short|duty|/ˈduːti/|n.职责",
"The fridge is almost empty, let's go grocery shopping.|冰箱快空了，去采购点吃的吧。|daily|家务/采购|long|grocery|/ˈɡroʊsəri/|n.食品杂货",
"Remember to water the plants while I'm away.|我不在的时候记得浇花。|daily|家务/浇花|long|water|/ˈwɔːtər/|v.浇水",
"I'll vacuum the living room after dinner.|晚饭后我来吸客厅的地。|daily|家务/打扫|short|vacuum|/ˈvækjuːm/|v.吸尘",
"The heating isn't working properly again.|暖气又不太好使了。|daily|居家/报修|short|heating|/ˈhiːtɪŋ/|n.供暖",
"Could you fix the leaky faucet in the kitchen?|能修一下厨房漏水的龙头吗？|daily|居家/报修|long|leaky|/ˈliːki/|adj.漏的",
"I'm beat, let's order takeout tonight.|我累瘫了，今晚点外卖吧。|daily|居家/外卖|short|takeout|/ˈteɪkaʊt/|n.外卖",
"What should we watch after dinner tonight?|今晚饭后看什么？|daily|居家/休闲|short|watch|/wɑtʃ/|v.观看",
"I need to charge my phone before we head out.|出门前我得先充会儿手机。|daily|居家/充电|long|head out|/hɛd aʊt/|phr.出门",
"Did you lock the door and turn off the stove?|你锁门关火了吗？|daily|居家/安全|short|lock|/lɑk/|v.锁",
"I'm off to bed, don't stay up too late.|我睡了，你别熬太晚。|daily|居家/作息|short|stay up|/steɪ ʌp/|phr.熬夜",
"I have a deadline coming up this Friday.|我这周五有个截止日期。|daily|工作/进度|short|deadline|/ˈdɛdlaɪn/|n.截止日期",
"Could you cover for me at the meeting tomorrow?|明天的会能替我顶一下吗？|daily|工作/代班|long|cover|/ˈkʌvər/|v.代班",
"Let's touch base after lunch on this project.|午饭后我们碰一下这个项目。|daily|工作/沟通|long|touch base|/tʌtʃ beɪs/|phr.沟通进展",
"I'll send you the report by end of day.|今天下班前我把报告发给你。|daily|工作/交付|short|end of day|/ɛnd əv deɪ/|phr.下班前",
"Sorry to interrupt, but there's an urgent call for you.|抱歉打扰，有个你的紧急电话。|daily|工作/打扰|long|interrupt|/ˌɪntəˈrʌpt/|v.打断",
"Good job on closing that big deal, well done.|拿下了那个大单，干得漂亮。|daily|工作/祝贺|short|well done|/wɛl dʌn/|phr.干得好",
"Let's call it a day and grab some dinner.|今天就到这儿吧，去吃点东西。|daily|工作/收工|short|call it a day|/kɔl ɪt ə deɪ/|phr.到此为止",
"I'm completely swamped with work this week.|这周我忙得不可开交。|daily|工作/忙碌|short|swamped|/swɑmpt/|adj.忙翻的",
"Could you send me the files again? They didn't come through.|能把文件再发一次吗？没收到。|daily|工作/文件|long|come through|/kʌm θruː/|phr.传送成功",
"Let me double-check the numbers before we send it out.|发出去之前我再核对一下数字。|daily|工作/核对|long|double-check|/ˈdʌbəl tʃɛk/|phr.复核",
"I'm off next week for a family trip.|我下周休假，全家出游。|daily|工作/休假|short|off|/ɔːf/|adj.休假的",
"First day back at work, feeling a bit rusty.|复工第一天，感觉有点生疏。|daily|工作/状态|long|rusty|/ˈrʌsti/|adj.生疏的",
"Could you explain this grammar point one more time?|能再讲一遍这个语法点吗？|daily|学习/请教|short|grammar|/ˈɡræmər/|n.语法",
"How do you memorize new words so fast?|你怎么记新单词那么快？|daily|学习/方法|short|memorize|/ˈmɛməraɪz/|v.记忆",
"I've been learning English for about six months now.|我学英语大概有六个月了。|daily|学习/进度|short|learning|/ˈlɜːrnɪŋ/|v.学习(现在分词)",
"Practice makes perfect, keep at it.|熟能生巧，坚持住。|daily|学习/鼓励|short|practice makes perfect|/ˈpræktɪs meɪks ˈpɜːrfɪkt/|phr.熟能生巧",
"Could you correct my pronunciation if I'm wrong?|如果我发音错了能帮我纠正吗？|daily|学习/纠正|long|pronunciation|/prəˌnʌnsiˈeɪʃən/|n.发音",
"I read a couple of pages every night before sleep.|我每晚睡前读几页书。|daily|学习/阅读|short|a couple of|/ə ˈkʌpəl əv/|phr.几个",
"What does this word mean in this context?|这个词在这个语境里是什么意思？|daily|学习/词义|long|context|/ˈkɑntɛkst/|n.语境",
"How long did it take you to become fluent?|你学到流利花了多久？|daily|学习/请教|short|fluent|/ˈfluːənt/|adj.流利的",
"I didn't get enough sleep last night.|我昨晚没睡够。|daily|健康/睡眠|short|enough|/ɪˈnʌf/|adj.足够的",
"You look a little pale, are you okay?|你脸色有点苍白，没事吧？|daily|健康/观察|short|pale|/peɪl/|adj.苍白的",
"I've got a runny nose and a slight fever.|我流鼻涕还有点低烧。|daily|健康/症状|long|runny nose|/ˈrʌni noʊz/|phr.流鼻涕",
"You should see a doctor if it doesn't improve.|要是不见好就该去看医生。|daily|健康/建议|long|improve|/ɪmˈpruːv/|v.改善",
"Drink plenty of water and get some rest.|多喝水，好好休息。|daily|健康/建议|short|plenty of|/ˈplɛni əv/|phr.大量的",
"I try to go for a run every other morning.|我尽量每隔一天晨跑一次。|daily|健康/锻炼|short|every other|/ˈɛvri ˈʌðər/|phr.每隔",
"I've cut down on coffee recently.|我最近咖啡喝少了。|daily|健康/饮食|short|cut down|/kʌt daʊn/|phr.减少摄入",
"Remember to stretch before you work out.|运动前记得拉伸。|daily|健康/运动|short|stretch|/strɛtʃ/|v.拉伸",
"My back hurts from sitting too long.|坐太久我背疼。|daily|健康/劳损|short|back|/bæk/|n.背部",
"You should take breaks from the screen more often.|你应该更常离开屏幕休息一下。|daily|健康/建议|long|screen|/skriːn/|n.屏幕",
"Have you taken your medicine this morning?|今早吃药了吗？|daily|健康/服药|short|medicine|/ˈmɛdɪsɪn/|n.药",
"I much prefer tea to coffee, honestly.|说实话，比起咖啡我更喜欢茶。|daily|饮食/偏好|short|prefer|/prɪˈfɜːr/|v.更喜欢",
"This soup tastes a bit too salty for me.|这汤对我来说有点太咸。|daily|饮食/口味|short|salty|/ˈsɔlti/|adj.咸的",
"I'm trying to eat more vegetables these days.|我最近尽量多吃蔬菜。|daily|饮食/健康|short|these days|/ðiz deɪz/|phr.近来",
"Help yourself to anything in the fridge.|冰箱里的东西随便吃。|daily|餐桌/招待|short|help yourself|/hɛlp jʊrˈsɛlf/|phr.请自便",
"This is my favorite dish at this place.|这是这家店我最爱的一道菜。|daily|餐桌/夸赞|short|favorite|/ˈfeɪvərɪt/|adj.最喜欢的",
"Would you like some more rice?|再来点米饭吗？|daily|餐桌/招待|short|some more|/sʌm mɔr/|phr.再来点",
"I'm stuffed, I really can't eat any more.|我饱了，真吃不下了。|daily|餐桌/饱腹|short|stuffed|/stʌft/|adj.吃撑的",
"Let me get this round of drinks.|这轮酒水我来请。|daily|餐桌/请客|short|round|/raʊnd/|n.一轮",
"If I were you, I'd take the earlier train.|我要是你的话就坐早一点的车。|daily|建议/劝告|long|if I were you|/ɪf aɪ wɜr juː/|phr.如果我是你",
"You'd better book the tickets in advance.|你最好提前订票。|daily|建议/劝告|short|in advance|/ɪn ədˈvæns/|phr.提前",
"Why don't you give it another try?|你为什么不再试一次？|daily|建议/鼓励|short|give a try|/ɡɪv ə traɪ/|phr.试一下",
"It might be worth checking the reviews first.|也许值得先看看评价。|daily|建议/参考|long|review|/rɪˈvjuː/|n.评价",
"Have you thought about asking for a raise?|你考虑过要求加薪吗？|daily|建议/职场|long|raise|/reɪz/|n.加薪",
"I strongly recommend backing up your files.|我强烈建议备份文件。|daily|建议/提醒|long|back up|/bæk ʌp/|phr.备份",
"You could always ask the front desk for help.|你随时可以找前台帮忙。|daily|建议/求助|short|always|/ˈɔlweɪz/|adv.随时",
"Whatever you decide, I'll support you.|无论你怎么决定，我都支持你。|daily|建议/支持|short|support|/səˈpɔrt/|v.支持",
"It's up to you, but I'd go with the blue one.|你定，不过我会选蓝色的。|daily|建议/选择|long|go with|/ɡoʊ wɪð/|phr.选择",
"Trust your gut on this one.|这件事相信你的直觉。|daily|建议/直觉|short|gut|/ɡʌt/|n.直觉",
"I don't want to push you, but time is running out.|我不想催你，但时间不多了。|daily|建议/催促|long|push|/pʊʃ/|v.催促",
"Looks like rain again, isn't it?|看起来又要下雨了，是吧？|daily|天气/闲聊|short|look like|/lʊk laɪk/|phr.看起来",
"The weather has been lovely all week.|这一周天气都很好。|daily|天气/描述|short|lovely|/ˈlʌvli/|adj.宜人的",
"It's supposed to snow tonight, so drive carefully.|今晚应该会下雪，开车小心。|daily|天气/提醒|long|be supposed to|/bi səˈpoʊzd tuː/|phr.按理应当",
"What's the temperature like outside?|外面气温怎么样？|daily|天气/气温|short|temperature|/ˈtɛmprətʃər/|n.气温",
"Autumn is the best season in Chengdu, I think.|我觉得成都是秋天最好。|daily|天气/季节|long|autumn|/ˈɔtəm/|n.秋天",
"Mind the step when you come in.|进来时小心台阶。|daily|提醒/安全|short|mind|/maɪnd/|v.注意",
"Don't forget your umbrella on your way out.|出门别忘了带伞。|daily|提醒/物品|short|on your way|/ɑn jʊr weɪ/|phr.在路上",
"Watch your step, the floor is wet.|小心脚下，地面湿滑。|daily|提醒/安全|short|wet|/wɛt/|adj.湿的",
"Careful, the plate is burning hot.|小心，盘子特别烫。|daily|提醒/高温|short|burning|/ˈbɜːrnɪŋ/|adj.灼热的",
"Make sure you bring your ID card with you.|记得带上身份证。|daily|提醒/证件|short|make sure|/meɪk ʃʊr/|phr.确保",
"Happy birthday! Make a wish before you blow out the candles.|生日快乐！吹蜡烛前许个愿。|daily|祝贺/生日|long|make a wish|/meɪk ə wɪʃ/|phr.许愿",
"Congratulations on your new job!|恭喜你找到新工作！|daily|祝贺/工作|short|congratulations|/kənˌɡrætʃəˈleɪʃənz/|n.祝贺",
"Best wishes for your wedding day.|祝你们新婚快乐。|daily|祝贺/婚礼|short|best wishes|/bɛst ˈwɪʃɪz/|phr.美好祝愿",
"Well done on passing the exam!|恭喜通过考试！|daily|祝贺/考试|short|pass|/pæs/|v.通过",
"Good luck with your interview tomorrow!|祝你明天面试顺利！|daily|祝贺/祝福|short|good luck|/ɡʊd lʌk/|phr.好运",
"Happy New Year to you and your family.|祝你和家人新年快乐。|daily|祝贺/节日|short|New Year|/nu jɪr/|phr.新年",
"Enjoy your trip and take lots of photos!|旅途愉快，多拍点照片！|daily|祝福/出行|short|enjoy|/ɪnˈdʒɔɪ/|v.享受",
"Get well soon, we all miss you here.|早日康复，我们都很想你。|daily|祝福/康复|short|get well|/ɡɛt wɛl/|phr.康复",
]
