# -*- coding: utf-8 -*-
# 语料池 1/5：旅游 · 机场/出入境/交通/问路（ids 101-280）
# 格式：en|zh|theme|category|length|关键词|关键词音标|词性+释义
RAW = [
"I'd like to check in for the ten a.m. flight to London.|我想办理上午十点飞伦敦航班的值机。|travel|机场/值机|short|check in|/tʃɛk ɪn/|phr.办理登机手续",
"Is there a self-service kiosk around here?|这附近有自助值机机吗？|travel|机场/值机|short|kiosk|/ˈkiːɑːsk/|n.自助服务亭",
"Could I get a window seat this time?|这次能给我靠窗的座位吗？|travel|机场/值机|short|window seat|/ˈwɪndoʊ siːt/|phr.靠窗座位",
"Do I need to check in online beforehand?|我需要提前在网上值机吗？|travel|机场/值机|short|beforehand|/bɪˈfɔːrhænd/|adv.事先",
"What's the baggage allowance for economy class?|经济舱的行李额度是多少？|travel|机场/值机|short|allowance|/əˈlaʊəns/|n.限额",
"The check-in counter closes forty minutes before departure.|值机柜台在起飞前四十分钟关闭。|travel|机场/值机|long|departure|/dɪˈpɑːrtʃər/|n.出发",
"Can I pay for the extra bag at the counter?|超重的行李可以在这儿柜台付吗？|travel|机场/值机|short|extra|/ˈɛkstrə/|adj.额外的",
"Is the flight on schedule today?|今天的航班准点吗？|travel|机场/值机|short|on schedule|/ɑn ˈskɛdʒuːl/|phr.准点",
"I have a connecting flight to catch at eight.|我八点还有一趟转机要赶。|travel|机场/转机|short|connecting flight|/kəˈnɛktɪŋ flaɪt/|phr.转接班机",
"Where should I go for my transfer?|我转机应该往哪儿走？|travel|机场/转机|short|transfer|/ˈtrænsfɜːr/|n.转机",
"Do I need to pick up my luggage and check it in again?|我需要取出行李重新托运吗？|travel|机场/转机|long|pick up|/pɪk ʌp/|phr.领取",
"How much layover time do I have between the flights?|两班航班之间我有多少中转时间？|travel|机场/转机|long|layover|/ˈleɪoʊvər/|n.中转停留",
"Is one hour enough for the connection?|转机一小时够吗？|travel|机场/转机|short|connection|/kəˈnɛkʃən/|n.衔接联程",
"I missed my connection because of the delay.|因为延误我没赶上转机。|travel|机场/延误|short|delay|/dɪˈleɪ/|n.延误",
"Will the airline put me on the next flight for free?|航空公司会免费帮我改到下一班吗？|travel|机场/延误|long|airline|/ˈerlaɪn/|n.航空公司",
"Is there any compensation for the delayed flight?|航班延误有补偿吗？|travel|机场/延误|short|compensation|/ˌkɑmpenˈseɪʃən/|n.补偿",
"How long is the flight expected to be delayed?|预计延误多久？|travel|机场/延误|short|expected|/ɪkˈspɛktɪd/|adj.预期的",
"Where can I claim my checked luggage?|我在哪儿提取托运行李？|travel|机场/行李|short|claim|/kleɪm/|v.认领",
"One of my suitcases didn't come out.|我的一个行李箱没出来。|travel|机场/行李|short|suitcase|/ˈsuːtkeɪs/|n.行李箱",
"My luggage seems to be damaged.|我的行李好像被弄坏了。|travel|机场/行李|short|damaged|/ˈdæmɪdʒd/|adj.损坏的",
"Could you help me lift this bag onto the belt?|能帮我把这个包抬上传送带吗？|travel|机场/行李|short|belt|/bɛlt/|n.传送带",
"Is there a trolley I can use nearby?|附近有行李推车可以用吗？|travel|机场/行李|short|trolley|/ˈtrɑːli/|n.手推车",
"I'd like to report a lost suitcase, please.|我想报失一个行李箱。|travel|机场/行李|short|report|/rɪˈpɔːrt/|v.报告",
"Here's my claim tag for the missing bag.|这是我丢失行李的提取标签。|travel|机场/行李|short|tag|/tæɡ/|n.标签",
"Passport and boarding pass, please.|请出示护照和登机牌。|travel|机场/安检|short|boarding pass|/ˈbɔːrdɪŋ pæs/|phr.登机牌",
"Do I need to take my laptop out of the bag?|我需要把笔记本电脑从包里拿出来吗？|travel|机场/安检|long|laptop|/ˈlæptɑp/|n.笔记本电脑",
"Please put your liquids in this tray.|请把液体放进这个托盘。|travel|机场/安检|short|tray|/treɪ/|n.托盘",
"Am I allowed to bring this water bottle through?|这个水瓶能带过去吗？|travel|机场/安检|short|allowed|/əˈlaʊd/|adj.被允许的",
"What's the purpose of your visit?|您此行的目的是什么？|travel|出入境/通关|short|purpose|/ˈpɜːrpəs/|n.目的",
"I'm here for tourism for about a week.|我来旅游，大概待一周。|travel|出入境/通关|short|tourism|/ˈtʊrɪzəm/|n.旅游",
"How long will you be staying in the country?|您在这个国家停留多久？|travel|出入境/通关|short|stay|/steɪ/|v.停留",
"Here are my passport and return ticket.|这是我的护照和返程机票。|travel|出入境/通关|short|return ticket|/rɪˈtɜːrn ˈtɪkɪt/|phr.返程票",
"Where should I go through customs?|海关从哪儿过？|travel|出入境/通关|short|customs|/ˈkʌstəmz/|n.海关",
"Do I have anything to declare? Nothing to declare.|我有什么要申报的吗？没有要申报的。|travel|出入境/通关|long|declare|/dɪˈklɛr/|v.申报",
"Could you tell me where the departure gate is?|能告诉我登机口在哪儿吗？|travel|机场/登机|short|gate|/ɡeɪt/|n.登机口",
"Has boarding started for gate twenty-two?|二十二号登机口开始登机了吗？|travel|机场/登机|short|boarding|/ˈbɔːrdɪŋ/|n.登机",
"What time does boarding begin?|什么时候开始登机？|travel|机场/登机|short|begin|/bɪˈɡɪn/|v.开始",
"Is this the right line for gate fifteen?|这是去十五号登机口的队伍吗？|travel|机场/登机|short|line|/laɪn/|n.队列",
"Could you call a taxi for me, please?|能帮我叫辆出租车吗？|travel|交通/打车|short|call a taxi|/kɔːl ə ˈtæksi/|phr.叫出租车",
"Roughly how much is it to the city center by taxi?|打车到市中心大概多少钱？|travel|交通/打车|long|roughly|/ˈrʌfli/|adv.大约",
"Do you take credit cards or cash only?|你们刷卡还是只收现金？|travel|交通/打车|short|cash|/kæʃ/|n.现金",
"Could you open the trunk for my luggage?|能打开后备箱放行李吗？|travel|交通/打车|short|trunk|/trʌŋk/|n.后备箱",
"Please drop me off at the main entrance.|请让我在正门下车。|travel|交通/打车|short|drop off|/drɑp ɔːf/|phr.让…下车",
"Could you slow down a little, please?|能开慢一点吗？|travel|交通/打车|short|slow down|/sloʊ daʊn/|phr.减速",
"Keep the change, thank you.|不用找了，谢谢。|travel|交通/打车|short|change|/tʃeɪndʒ/|n.零钱",
"Is the meter running?|计价器开着吗？|travel|交通/打车|short|meter|/ˈmiːtər/|n.计价器",
"Which subway line goes to the museum?|哪条地铁线到博物馆？|travel|交通/地铁|short|subway line|/ˈsʌbweɪ laɪn/|phr.地铁线路",
"I'd like a single ticket to Central Station.|我买一张去中央车站的单程票。|travel|交通/购票|short|single ticket|/ˈsɪŋɡəl ˈtɪkɪt/|phr.单程票",
"Is a day pass worth it for getting around?|买张一日票划算吗？|travel|交通/购票|long|day pass|/deɪ pæs/|phr.一日通票",
"Does this train stop at every station?|这趟车每站都停吗？|travel|交通/火车|short|station|/ˈsteɪʃən/|n.车站",
"Which platform does the express leave from?|快车从几号站台发车？|travel|交通/火车|short|platform|/ˈplætfɔːrm/|n.站台",
"Where do I get off for the old town?|去老城应该在哪站下？|travel|交通/乘车|short|get off|/ɡɛt ɔːf/|phr.下车",
"Could you let me know when we arrive?|到站时能告诉我一声吗？|travel|交通/乘车|short|arrive|/əˈraɪv/|v.到达",
"How often do the buses run on this route?|这条线路的公交多久一班？|travel|交通/公交|long|route|/ruːt/|n.线路",
"Does this bus go all the way to the beach?|这趟公交一直到海滩吗？|travel|交通/公交|short|all the way|/ɔːl ðə weɪ/|phr.一直",
"Where's the nearest bus stop?|最近的公交站在哪儿？|travel|交通/公交|short|bus stop|/bʌs stɑp/|phr.公交站",
"I'd like to rent a compact car for three days.|我想租一辆紧凑型车，租三天。|travel|交通/租车|short|compact|/ˈkɑmpækt/|adj.小型的",
"Does the price include full insurance?|价格里含全险吗？|travel|交通/租车|short|insurance|/ɪnˈʃʊrəns/|n.保险",
"Do I need an international driving permit?|我需要国际驾照吗？|travel|交通/租车|short|permit|/ˈpɜːrmɪt/|n.许可证",
"Is the fuel policy full-to-full?|油量政策是满油取还吗？|travel|交通/租车|short|fuel|/ˈfjuːəl/|n.燃料",
"Where can I return the car after hours?|下班后我可以在哪儿还车？|travel|交通/租车|short|after hours|/ˈæftər ˈaʊərz/|phr.下班时间后",
"Is there a gas station on the way to the highway?|去高速的路上有加油站吗？|travel|交通/加油|long|gas station|/ɡæs ˈsteɪʃən/|phr.加油站",
"Could you fill it up with regular, please?|请给我加满普通汽油。|travel|交通/加油|short|fill up|/fɪl ʌp/|phr.加满",
"Is parking free around here on weekends?|这一带周末停车免费吗？|travel|交通/停车|long|parking|/ˈpɑːrkɪŋ/|n.停车",
"Do you validate parking for customers?|你们为顾客提供停车券吗？|travel|交通/停车|short|validate|/ˈvælɪdeɪt/|v.使有效",
"Excuse me, which way is the train station?|打扰一下，火车站往哪边走？|travel|问路/方向|short|which way|/wɪtʃ weɪ/|phr.哪边",
"Go straight for two blocks, then turn left.|直走两个街区，然后左转。|travel|问路/指路|long|block|/blɑk/|n.街区",
"It's just around the corner on your right.|就在拐角处，你右手边。|travel|问路/指路|short|corner|/ˈkɔːrnər/|n.拐角",
"Is it within walking distance from here?|从这里步行能到吗？|travel|问路/距离|short|walking distance|/ˈwɔːkɪŋ ˈdɪstəns/|phr.步行距离",
"How far is the airport from downtown?|机场离市中心有多远？|travel|问路/距离|short|downtown|/ˈdaʊntaʊn/|n.市中心",
"Am I heading in the right direction for the park?|去公园我是走对方向了吗？|travel|问路/方向|long|direction|/dəˈrɛkʃən/|n.方向",
"Could you show me on the map where we are?|能在地图上指给我看我们在哪吗？|travel|问路/地图|long|map|/mæp/|n.地图",
"Is there a shortcut to avoid the traffic?|有没有能避开堵车的近路？|travel|问路/路线|short|shortcut|/ˈʃɔːrtkʌt/|n.近路",
"Cross the bridge and keep going until you see the tower.|过了桥一直走，直到看见那座塔。|travel|问路/指路|long|bridge|/brɪdʒ/|n.桥",
"Where is the tourist information center?|旅游咨询中心在哪儿？|travel|问路/便民|short|tourist|/ˈtʊrɪst/|n.游客",
"Is the museum within this district?|博物馆在这个区里吗？|travel|问路/地点|short|district|/ˈdɪstrɪkt/|n.区域",
"Which exit should I take for the shopping mall?|去购物中心该走哪个出口？|travel|问路/出口|short|exit|/ˈɛɡzɪt/|n.出口",
"Are there any landmarks I should look out for?|有什么标志性建筑我可以留意吗？|travel|问路/地标|long|landmark|/ˈlændmɑːrk/|n.地标",
"Can I walk there before dark?|天黑前我能走到那儿吗？|travel|问路/时间|short|dark|/dɑːrk/|n.天黑",
"I'd like to book a double room for two nights.|我想订一间双人房，住两晚。|travel|酒店/预订|short|double room|/ˈdʌbəl ruːm/|phr.双人房",
"Do you have anything available for tonight?|今晚还有空房吗？|travel|酒店/预订|short|available|/əˈveɪləbəl/|adj.可用的",
"What's the rate for a single room per night?|单人房每晚多少钱？|travel|酒店/预订|short|rate|/reɪt/|n.价格",
"Is there a discount for staying a whole week?|住一整周有折扣吗？|travel|酒店/预订|short|discount|/ˈdɪskaʊnt/|n.折扣",
"I have a reservation under the name Wang.|我用王的名字订了房。|travel|酒店/入住|short|reservation|/ˌrɛzərˈveɪʃən/|n.预订",
"Could I see your passport for a moment, please?|能出示一下您的护照吗？|travel|酒店/入住|short|passport|/ˈpæspɔːrt/|n.护照",
"What time is check-in usually?|一般几点可以入住？|travel|酒店/入住|short|check-in|/ˈtʃɛk ɪn/|n.入住",
"Could I leave my luggage here until the room is ready?|房间好之前我能把行李寄存在这儿吗？|travel|酒店/寄存|long|luggage|/ˈlʌɡɪdʒ/|n.行李",
"I'm checking out today and would like to settle my bill.|我今天退房，想结一下账。|travel|酒店/退房|long|settle|/ˈsɛtəl/|v.结清",
"What time do we have to check out by?|退房时间最晚到几点？|travel|酒店/退房|short|check out|/tʃɛk aʊt/|phr.退房",
"Could you give me a receipt for the payment?|能给我一张付款收据吗？|travel|酒店/退房|short|receipt|/rɪˈsiːt/|n.收据",
"Is there a late check-out option available?|有延迟退房的服务吗？|travel|酒店/退房|short|late|/leɪt/|adj.晚的",
"Could I have a wake-up call at six tomorrow?|明早六点能给我个叫醒电话吗？|travel|酒店/服务|short|wake-up call|/ˈweɪk ʌp kɔːl/|phr.叫醒服务",
"The air conditioner in my room isn't working.|我房间的空调坏了。|travel|酒店/报修|short|air conditioner|/ˈer kənˌdɪʃənər/|phr.空调",
"There's no hot water this morning.|今天早上没有热水。|travel|酒店/报修|short|hot water|/hɑt ˈwɔːtər/|phr.热水",
"Could someone take a look at the shower?|能派个人来看看淋浴吗？|travel|酒店/报修|short|shower|/ˈʃaʊər/|n.淋浴",
"Could you bring an extra blanket to room 305?|能给305房间多送一条毯子吗？|travel|酒店/服务|short|blanket|/ˈblæŋkɪt/|n.毯子",
"Is room service available around the clock?|客房送餐服务是全天候的吗？|travel|酒店/服务|short|room service|/ruːm ˈsɜːrvɪs/|phr.客房服务",
"Could you have my suit dry-cleaned by tomorrow?|我的西装能明天之前干洗好吗？|travel|酒店/服务|long|dry-cleaned|/ˈdraɪ kliːnd/|v.干洗",
"The room next door is too noisy at night.|隔壁房间晚上太吵了。|travel|酒店/换房|short|noisy|/ˈnɔɪzi/|adj.吵闹的",
"Would it be possible to move to a quieter room?|能换到安静一点的房间吗？|travel|酒店/换房|long|quieter|/ˈkwaɪətər/|adj.更安静的",
"The view from this room is amazing.|这间房的景色太棒了。|travel|酒店/房间|short|view|/vjuː/|n.景色",
"Does the room come with a safe for valuables?|房间里有放贵重物品的保险箱吗？|travel|酒店/房间|long|safe|/seɪf/|n.保险箱",
"Is the minibar included in the room rate?|迷你吧的费用含在房费里吗？|travel|酒店/房间|short|minibar|/ˈmɪnibɑːr/|n.迷你酒吧",
"Could I get a spare key card for my partner?|能给我同伴再拿一张房卡吗？|travel|酒店/房间|short|spare|/spɛr/|adj.备用的",
"I'd like to extend my stay for two more nights.|我想再多住两晚。|travel|酒店/续住|short|extend|/ɪkˈstɛnd/|v.延长",
"Is the room rate the same if I stay longer?|多住几晚房价一样吗？|travel|酒店/续住|short|stay|/steɪ/|v.逗留",
"Do you offer airport pickup for guests?|你们提供接机服务吗？|travel|酒店/服务|short|pickup|/ˈpɪkʌp/|n.接载",
"Is breakfast served in the lobby or in the restaurant?|早餐在大堂还是在餐厅供应？|travel|酒店/餐饮|long|lobby|/ˈlɑːbi/|n.大堂",
"What time does breakfast start in the morning?|早餐早上几点开始？|travel|酒店/餐饮|short|serve|/sɜːrv/|v.供应",
"Could you recommend a local dish worth trying?|能推荐一道值得尝尝的本地菜吗？|travel|餐厅/推荐|short|dish|/dɪʃ/|n.菜肴",
"Do you have any tables free for two tonight?|今晚还有两个人的位子吗？|travel|餐厅/订位|short|table|/ˈteɪbəl/|n.餐桌",
"I'd like to make a reservation for six at seven p.m.|我想订今晚七点六个人的位子。|travel|餐厅/订位|long|reservation|/ˌrɛzərˈveɪʃən/|n.预订",
"We'll take the table by the window if possible.|可以的话我们坐靠窗的位子。|travel|餐厅/座位|long|if possible|/ɪf ˈpɑsəbəl/|phr.如果可能",
"Could I see the menu, please?|能给我看下菜单吗？|travel|餐厅/点餐|short|menu|/ˈmɛnjuː/|n.菜单",
"What do you recommend as a starter?|前菜你推荐什么？|travel|餐厅/点餐|short|starter|/ˈstɑːrtər/|n.前菜",
"I'll have the same as what she's having.|我点一份和她一样的。|travel|餐厅/点餐|short|the same|/ðə seɪm/|phr.一样的",
"Could I get this without onions?|这个能不放洋葱吗？|travel|餐厅/忌口|short|onion|/ˈʌnjən/|n.洋葱",
"Is this dish very spicy?|这道菜很辣吗？|travel|餐厅/忌口|short|spicy|/ˈspaɪsi/|adj.辣的",
"I'm allergic to peanuts, so please be careful.|我对花生过敏，麻烦注意一下。|travel|餐厅/忌口|long|allergic|/əˈlɜːrdʒɪk/|adj.过敏的",
"Could you tell me what's in this sauce?|能告诉我这个酱汁里有什么吗？|travel|餐厅/忌口|short|sauce|/sɔːs/|n.酱汁",
"Does it contain any seafood?|这里面有海鲜吗？|travel|餐厅/忌口|short|seafood|/ˈsiːfuːd/|n.海鲜",
"I'll order the set meal for two.|我点两人份的套餐。|travel|餐厅/点餐|short|set meal|/sɛt miːl/|phr.套餐",
"How would you like your steak done?|您的牛排要几分熟？|travel|餐厅/点餐|short|steak|/steɪk/|n.牛排",
"Medium well for me, please.|请给我七分熟。|travel|餐厅/点餐|short|medium well|/ˈmiːdiəm wɛl/|phr.七分熟",
"Could we get some more water for the table?|能再给我们添点水吗？|travel|餐厅/服务|short|table|/ˈteɪbəl/|n.桌",
"This isn't what I ordered, I'm afraid.|抱歉，这不是我点的。|travel|餐厅/服务|short|ordered|/ˈɔːrdərd/|v.点餐(pp.)",
"The food was excellent, thank you.|菜非常好吃，谢谢。|travel|餐厅/夸赞|short|excellent|/ˈɛksələnt/|adj.极好的",
"Could we have the bill, please?|可以结账了吗？|travel|餐厅/结账|short|bill|/bɪl/|n.账单",
"Could we split the bill three ways?|我们能三人均摊结账吗？|travel|餐厅/结账|short|split|/splɪt/|v.分摊",
"Is service charge included in the bill?|账单里含服务费吗？|travel|餐厅/结账|short|service charge|/ˈsɜːrvɪs tʃɑːrdʒ/|phr.服务费",
"Keep the rest as your tip.|剩下的当小费给你。|travel|餐厅/小费|short|tip|/tɪp/|n.小费",
"I'd like this to take away, please.|这个请给我打包带走。|travel|餐厅/打包|short|take away|/teɪk əˈweɪ/|phr.外带",
"Do you do delivery to nearby hotels?|你们往附近酒店送外卖吗？|travel|快餐/外卖|short|delivery|/dɪˈlɪvəri/|n.外卖配送",
"I'll have a burger with fries to go.|我要一个汉堡加薯条，带走。|travel|快餐/点单|short|fries|/fraɪz/|n.薯条",
"For here or to go?|在这儿吃还是带走？|travel|快餐/点单|short|to go|/tə ɡoʊ/|phr.带走",
"Could I get extra ketchup packets?|能多给几包番茄酱吗？|travel|快餐/点单|short|ketchup|/ˈkɛtʃəp/|n.番茄酱",
]
