# -*- coding: utf-8 -*-
# 语料池 8/8：日常与旅游补充 · 收尾（凑满 900）
RAW = [
"It's ten minutes' walk from here.|从这里走过去十分钟。|travel|问路/距离|short|walk|/wɔk/|n.步行路程",
"Go past the bank and it's on your left.|过了银行就在你左手边。|travel|问路/指路|short|go past|/ɡoʊ pæst/|phr.经过",
"The entrance is at the back of the building.|入口在大楼后面。|travel|问路/位置|short|entrance|/ˈɛntrəns/|n.入口",
"You can't miss it, it's right next to the fountain.|就在喷泉旁边，你不会错过的。|travel|问路/地标|long|fountain|/ˈfaʊntən/|n.喷泉",
"Take the second turning on the right.|在第二个路口右转。|travel|问路/指路|short|turning|/ˈtɜrnɪŋ/|n.转弯处",
"The museum is across the street from the park.|博物馆在公园的马路对面。|travel|问路/位置|long|across|/əˈkrɔs/|prep.在对面",
"Where's the ticket office, please?|请问售票处在哪儿？|travel|观光/门票|short|ticket office|/ˈtɪkɪt ˈɔfɪs/|phr.售票处",
"Can I buy tickets online in advance?|能提前在网上买票吗？|travel|观光/门票|long|in advance|/ɪn ədˈvæns/|phr.提前",
"Is there a discount for booking online?|网上预订有折扣吗？|travel|观光/门票|long|book|/bʊk/|v.预订",
"How many people does the group tour take?|团体游一个团带多少人？|travel|观光/导览|long|group tour|/ɡruːp tʊr/|phr.团体游",
"Where's the meeting point for the day tour?|一日游的集合点在哪儿？|travel|观光/集合|long|meeting point|/ˈmiːtɪŋ pɔɪnt/|phr.集合点",
"What should I wear for this excursion?|这次短途游我该穿什么？|travel|观光/准备|short|excursion|/ɪkˈskɜrʒən/|n.短途游览",
"Are we allowed to feed the animals here?|这里可以喂动物吗？|travel|观光/规定|short|feed|/fiːd/|v.喂",
"Where can I rent a locker for the day?|我能在哪儿租个当日储物柜？|travel|观光/便民|long|locker|/ˈlɑkər/|n.储物柜",
"The view from the top is worth the climb.|山顶的景色爬上去也值。|travel|观光/评价|short|climb|/klaɪm/|n.攀登",
"Let's grab a quick bite before the show.|演出前咱们赶紧吃点东西。|travel|餐厅/快餐|long|grab a bite|/ɡræb ə baɪt/|phr.随便吃点",
"I'll have what's on special today.|我点今天的特价菜。|travel|餐厅/点餐|short|special|/ˈspɛʃəl/|n.特价菜",
"Is the tip included in the check here?|这里账单含小费吗？|travel|餐厅/小费|short|check|/tʃɛk/|n.账单",
"Could I see the dessert menu, please?|能看看甜点单吗？|travel|餐厅/点餐|short|dessert|/dɪˈzɜrt/|n.甜点",
"Anything to drink before you order?|点餐前想喝点什么吗？|travel|餐厅/服务|short|order|/ˈɔrdər/|v.点餐",
"This tastes absolutely divine.|这味道简直绝了。|travel|餐厅/夸赞|short|divine|/dɪˈvaɪn/|adj.极好的",
"Could I get this reheated, please?|能帮我热一下这个吗？|travel|餐厅/服务|short|reheat|/ˌriːˈhiːt/|v.重新加热",
"We'd like a table for four by the window.|我们想要靠窗四人桌。|travel|餐厅/订位|long|table for four|/ˈteɪbəl fɔr fɔr/|phr.四人桌",
"Is the water here free of charge?|这里的水免费吗？|travel|餐厅/询问|short|free of charge|/fri əv tʃɑrdʒ/|phr.免费",
"Do you have a table on the terrace?|露台有位子吗？|travel|餐厅/座位|short|terrace|/ˈtɛrəs/|n.露台",
"Excuse me, my order hasn't arrived yet.|打扰一下，我点的还没上。|travel|餐厅/催单|long|arrive|/əˈraɪv/|v.到达",
"Could I have a doggy bag for the rest?|剩下的能打包吗？|travel|餐厅/打包|short|doggy bag|/ˈdɔɡi bæɡ/|phr.打包袋",
"The portion sizes here are so generous.|这里的菜量真足。|travel|餐厅/评价|short|generous|/ˈdʒɛnərəs/|adj.大方的",
"Where's the nearest convenience store?|最近的便利店在哪儿？|travel|生活/购物|short|convenience store|/kənˈviːnjəns stɔr/|phr.便利店",
"Do you have any instant noodles here?|你们这儿有泡面吗？|travel|生活/购物|short|instant noodles|/ˈɪnstənt ˈnuːdəlz/|phr.泡面",
"Could you heat this up for me, please?|能帮我加热一下这个吗？|travel|生活/服务|short|heat up|/hiːt ʌp/|phr.加热",
"Do you sell phone chargers here?|这里卖手机充电器吗？|travel|生活/购物|short|charger|/ˈtʃɑrdʒər/|n.充电器",
"I'm just looking around, thank you.|我先随便看看，谢谢。|travel|购物/浏览|short|look around|/lʊk əˈraʊnd/|phr.随便看看",
"Could you show me where this is on the shelf?|能告诉我这在哪个货架吗？|travel|购物/找货|long|shelf|/ʃɛlf/|n.货架",
"Is there a loyalty card for this shop?|这家店有会员卡吗？|travel|购物/会员|short|loyalty card|/ˈlɔɪəlti kɑrd/|phr.会员卡",
"Could you gift-wrap this separately?|能把这个单独包装成礼物吗？|travel|购物/包装|short|separately|/ˈsɛpərətli/|adv.分开地",
"It's a little pricey for my budget.|对我的预算来说有点小贵。|travel|购物/评价|short|pricey|/ˈpraɪsi/|adj.昂贵的",
"I'll think about it and come back later.|我再考虑考虑，稍后再来。|travel|购物/犹豫|long|come back|/kʌm bæk/|phr.回来",
"Could I get a bag for these, please?|能给我个袋子装这些吗？|travel|购物/打包|short|bag|/bæɡ/|n.袋子",
"Does this come with a warranty?|这个带保修吗？|travel|购物/保修|short|come with|/kʌm wɪð/|phr.附带",
"My room key doesn't work anymore.|我的房卡刷不了了。|travel|酒店/报修|short|work|/wɜrk/|v.起作用",
"Is there a hair dryer in the room?|房间里有吹风机吗？|travel|酒店/设施|short|hair dryer|/hɛr ˈdraɪər/|phr.吹风机",
"Could you send more towels to my room?|能再给我房间送几条毛巾吗？|travel|酒店/服务|short|towel|/ˈtaʊəl/|n.毛巾",
"The elevator is out of order, take the stairs.|电梯坏了，走楼梯吧。|travel|酒店/设施|long|out of order|/aʊt əv ˈɔrdər/|phr.故障",
"Is there a gym in the hotel?|酒店里有健身房吗？|travel|酒店/设施|short|gym|/dʒɪm/|n.健身房",
"Does the hotel have a pool on the rooftop?|酒店屋顶有泳池吗？|travel|酒店/设施|long|rooftop|/ˈruːftɑp/|n.屋顶",
"What's the total charge including tax?|含税总共多少钱？|travel|酒店/结账|short|including|/ɪnˈkluːdɪŋ/|prep.包含",
"Could you call a doctor to the room?|能请医生到房间来吗？|travel|应急/就医|short|call|/kɔl/|v.请来",
"I lost my room card somewhere in the lobby.|我的房卡落在大厅某处了。|travel|应急/遗失|long|lobby|/ˈlɑbi/|n.大厅",
"Where's the fire exit in this building?|这栋楼的消防通道在哪儿？|travel|应急/安全|short|fire exit|/ˈfaɪər ˈɛɡzɪt/|phr.消防出口",
"Is the water safe to brush teeth with?|这水刷牙安全吗？|travel|生活/饮水|long|brush teeth|/brʌʃ tiːθ/|phr.刷牙",
"Could you book a cab for six tomorrow morning?|能帮我订明早六点的出租车吗？|travel|交通/预约|long|cab|/kæb/|n.出租车",
"Is there a shuttle to the exhibition center?|有去会展中心的班车吗？|travel|交通/班车|long|exhibition|/ˌɛksɪˈbɪʃən/|n.展览",
"How much is the fare to the airport?|到机场车费多少？|travel|交通/费用|short|fare|/fɛr/|n.车费",
"Could you stop at that pharmacy on the way?|路上能在那个药店停一下吗？|travel|交通/要求|short|stop|/stɑp/|v.停靠",
"I'm allergic to shellfish, does this contain any?|我对贝类过敏，这个里面有吗？|travel|餐厅/忌口|long|shellfish|/ˈʃɛlfɪʃ/|n.贝类",
"Does this dish contain nuts of any kind?|这道菜里含任何坚果吗？|travel|餐厅/忌口|long|nut|/nʌt/|n.坚果",
"Is the milk in this fresh or powdered?|这里面用的是鲜奶还是奶粉？|travel|餐厅/询问|short|powdered|/ˈpaʊdərd/|adj.粉末的",
"Could I have it less oily, please?|能做得清淡点少油吗？|travel|餐厅/要求|short|oily|/ˈɔɪli/|adj.油腻的",
"Is the soup vegetarian friendly?|这个汤是素的吗？|travel|餐厅/忌口|short|vegetarian|/ˌvɛdʒəˈtɛriən/|adj.素食的",
"Where can I wash my hands around here?|这附近哪儿能洗手？|travel|公共/便民|short|wash hands|/wɑʃ hændz/|phr.洗手",
"Is smoking allowed on this floor?|这层楼可以吸烟吗？|travel|公共/规定|short|smoking|/ˈsmoʊkɪŋ/|n.吸烟",
"Where's the smoking area, please?|请问吸烟区在哪儿？|travel|公共/规定|short|area|/ˈɛriə/|n.区域",
"Could you keep it down after ten p.m.?|晚上十点后能小点声吗？|travel|公共/提醒|long|keep it down|/kip ɪt daʊn/|phr.放低音量",
"Sorry, this seat is reserved for elderly passengers.|抱歉，这是老年乘客专座。|travel|公共/礼让|long|reserved|/rɪˈzɜrvd/|adj.预留的",
"Please give up your seat for those in need.|请给有需要的人让座。|travel|公共/礼让|long|give up|/ɡɪv ʌp/|phr.让出",
"Where can I recycle plastic bottles here?|这儿的塑料瓶回收点在哪？|travel|公共/环保|long|recycle|/ˌriːˈsaɪkəl/|v.回收",
"Is there a water fountain to refill bottles?|有饮水机能灌瓶吗？|travel|公共/便民|long|refill|/ˌriːˈfɪl/|v.续水",
"How often does the shuttle bus run?|班车多久一班？|travel|交通/班车|short|shuttle bus|/ˈʃʌtəl bʌs/|phr.班车",
"Let me check the timetable first.|我先查下时刻表。|travel|交通/查询|short|timetable|/ˈtaɪmteɪbəl/|n.时刻表",
"The last train leaves at eleven forty.|末班车十一点四十发车。|travel|交通/时间|short|leave|/liːv/|v.出发",
"Which is faster, the bus or the metro?|公交和地铁哪个更快？|travel|交通/比较|short|metro|/ˈmɛtroʊ/|n.地铁",
"Could you put my bag in the overhead locker?|能帮我把包放进行李架吗？|travel|交通/乘车|long|overhead locker|/ˈoʊvərhɛd ˈlɑkər/|phr.行李架",
"Is anyone sitting in this aisle seat?|这个过道座有人坐吗？|travel|交通/乘车|long|aisle|/aɪl/|n.过道",
"Sorry, that seat is mine, I think.|不好意思，那个座位应该是我的。|travel|交通/座位|short|mine|/maɪn/|pron.我的",
"Would you mind swapping seats with me?|介意和我换个座吗？|travel|交通/座位|short|swap|/swɑp/|v.交换",
"How many stops are there before the airport?|到机场还有几站？|travel|交通/咨询|short|stop|/stɑp/|n.站",
"Let me know when we're two stops away.|还剩两站时告诉我一声。|travel|交通/提醒|short|away|/əˈweɪ/|adv.距…远",
"Where do I scan the ticket to get in?|进站在哪儿刷票？|travel|交通/进站|short|scan|/skæn/|v.扫描",
"Is this seat for priority passengers only?|这是爱心专座吗？|travel|公共/礼让|long|priority|/praɪˈɔrəti/|n.优先权",
"How deep is the pool at this hotel?|这家酒店的泳池多深？|travel|酒店/设施|short|deep|/diːp/|adj.深的",
"Is the pool heated in winter?|泳池冬天是温水的吗？|travel|酒店/设施|short|heated|/ˈhiːtɪd/|adj.加热的",
"Could I borrow an umbrella from the front desk?|能从前台借把伞吗？|travel|酒店/借用|long|borrow|/ˈbɑroʊ/|v.借用",
"Are pets allowed in the rooms?|房间里能带宠物吗？|travel|酒店/规定|short|pet|/pɛt/|n.宠物",
"Could you give me directions to the car rental desk?|能告诉我租车柜台怎么走吗？|travel|交通/租车|long|desk|/dɛsk/|n.柜台",
"Do you have GPS in the rental cars?|租车带导航吗？|travel|交通/租车|short|GPS|/ˌdʒi pi ˈɛs/|n.全球定位系统",
"Is insurance mandatory for renting a car here?|这儿租车必须买保险吗？|travel|交通/租车|long|mandatory|/ˈmændətɔri/|adj.强制的",
"The tank is half full, is that okay for return?|油箱还有半箱，还车这样可以吗？|travel|交通/还车|long|tank|/tæŋk/|n.油箱",
"Watch for pedestrians at the crossing.|过人行横道时注意行人。|travel|交通/提醒|short|pedestrian|/pəˈdɛstriən/|n.行人",
"Is parking validation available at this mall?|这家商场提供停车券吗？|travel|交通/停车|short|mall|/mɔl/|n.商场",
"The parking garage is full, let's find street parking.|停车场满了，找路边车位吧。|travel|交通/停车|long|garage|/ɡəˈrɑʒ/|n.车库",
"Could you drop me at the corner instead?|能让我在街角下吗？|travel|交通/要求|short|instead|/ɪnˈstɛd/|adv.改为",
"Turn on the meter, please.|请打表。|travel|交通/打车|short|meter|/ˈmiːtər/|n.计价器",
"Could you take the highway to save time?|能走高速省点时间吗？|travel|交通/打车|long|highway|/ˈhaɪweɪ/|n.高速公路",
"How much would it cost to go by toll road?|走收费路要花多少钱？|travel|交通/费用|long|toll road|/toʊl roʊd/|phr.收费公路",
"Let me grab my things and get out here.|我拿下东西在这儿下车。|travel|交通/下车|short|get out|/ɡɛt aʊt/|phr.下车",
"Are we almost at the destination?|我们快到目的地了吗？|travel|交通/确认|short|destination|/ˌdɛstəˈneɪʃən/|n.目的地",
"Where exactly do you want to go?|你具体想去哪儿？|travel|问路/确认|short|exactly|/ɪɡˈzæktli/|adv.确切地",
"Is it on this side of the river or the other?|是在河这边还是对岸？|travel|问路/位置|short|river|/ˈrɪvər/|n.河",
"Which floor is the rooftop bar on?|屋顶酒吧在几层？|travel|问路/位置|short|floor|/flɔr/|n.楼层",
"Take the elevator to the fifth and turn right.|坐电梯到五楼然后右转。|travel|问路/指路|long|elevator|/ˈɛlɪveɪtər/|n.电梯",
"Go down these stairs and it's straight ahead.|下这段楼梯，正前方就是。|travel|问路/指路|long|stairs|/stɛrz/|n.楼梯",
"It's the third door on your left down the hall.|沿走廊左手第三扇门。|travel|问路/指路|long|hall|/hɔl/|n.走廊",
"Where can I find the information desk?|咨询台在哪儿？|travel|公共/便民|short|information desk|/ˌɪnfərˈmeɪʃən dɛsk/|phr.咨询台",
"Could you point me to the nearest exit?|能给我指下最近的出口吗？|travel|公共/出口|short|point to|/pɔɪnt tuː/|phr.指向",
"Is there a first-aid station in this mall?|商场里有急救站吗？|travel|应急/急救|long|first aid|/fɜrst eɪd/|phr.急救",
"I feel a bit faint, could I sit down somewhere?|我有点头晕，能找地方坐坐吗？|travel|应急/不适|long|faint|/feɪnt/|adj.虚弱的",
"Could someone help me, my friend fell down!|有人能帮帮我吗，我朋友摔倒了！|travel|应急/求助|short|fall down|/fɔl daʊn/|phr.摔倒",
"Please call the police right away.|请立刻报警。|travel|应急/报警|short|right away|/raɪt əˈweɪ/|phr.立刻",
"I'd like to report a minor car accident.|我想报一起小剐蹭事故。|travel|应急/事故|long|accident|/ˈæksɪdənt/|n.事故",
"Nobody is hurt, but we need to exchange details.|没人受伤，但需要交换联系方式。|travel|应急/事故|long|exchange details|/ɪksˈtʃeɪndʒ ˈdiːteɪlz/|phr.交换信息",
"Where's the lost luggage office at this station?|车站的行李遗失办公室在哪儿？|travel|应急/遗失|long|office|/ˈɔfɪs/|n.办公室",
"Could you write down the address for the driver?|能给司机写一下地址吗？|travel|应急/沟通|long|write down|/raɪt daʊn/|phr.写下",
"Could you translate this sign for me, please?|能帮我翻译下这个标识吗？|travel|应急/沟通|short|translate|/ˈtrænzleɪt/|v.翻译",
"Where can I find a interpreter in town?|城里哪儿能找到口译？|travel|应急/沟通|long|interpreter|/ɪnˈtɜrprɪtər/|n.口译员",
"Is there an English-speaking doctor available?|有会说英语的医生吗？|travel|应急/就医|long|available|/əˈveɪləbəl/|adj.可找到的",
"Where's the nearest hospital with an ER?|最近的有急诊的医院在哪儿？|travel|应急/就医|short|ER|/ˌiː ˈɑr/|n.急诊室",
"Could you fill this prescription for me?|能帮我照这个处方配药吗？|travel|应急/药店|long|prescription|/prɪˈskrɪpʃən/|n.处方",
"Do you have medicine for motion sickness?|你们有晕车药吗？|travel|应急/药店|short|motion sickness|/ˈmoʊʃən ˌsɪknəs/|phr.晕车",
"Take one tablet twice a day after meals.|一天两次每次一片，饭后服。|travel|应急/服药|short|tablet|/ˈtæblət/|n.药片",
"Does this medicine make you drowsy?|这药吃了会犯困吗？|travel|应急/服药|short|drowsy|/ˈdraʊzi/|adj.困倦的",
"Where can I get a COVID test around here?|这附近哪儿能做核酸检测？|travel|应急/就医|long|test|/tɛst/|n.检测",
"I twisted my ankle on the trail.|我在山道上崴了脚踝。|travel|应急/受伤|short|twist|/twɪst/|v.扭伤",
"Could you get me some ice for the swelling?|能帮我拿点冰敷一下肿的地方吗？|travel|应急/受伤|long|swelling|/ˈswɛlɪŋ/|n.肿胀",
"Where's the nearest emergency exit sign?|最近的紧急出口标识在哪儿？|travel|应急/安全|short|emergency exit|/ɪˈmɜrdʒənsi ˈɛɡzɪt/|phr.紧急出口",
"Is the building being evacuated?|大楼正在疏散吗？|travel|应急/安全|short|evacuate|/ɪˈvækjueɪt/|v.疏散",
"Stay calm and follow the staff instructions.|保持冷静，听从工作人员指挥。|travel|应急/安抚|long|staff|/stæf/|n.工作人员",
"Where's the assembly point in an emergency?|紧急情况下的集合点在哪儿？|travel|应急/安全|long|assembly point|/əˈsɛmbli pɔɪnt/|phr.集合点",
"My phone died and I need to call my family.|我手机没电了，需要联系家人。|travel|应急/求助|long|die|/daɪ/|v.没电",
"Could I borrow your phone for one quick call?|能借用你手机打个简短电话吗？|travel|应急/求助|long|quick|/kwɪk/|adj.快速的",
"I'm locked out of my room, can you help?|我被锁在房间外面了，能帮忙吗？|travel|应急/求助|short|locked out|/lɑkt aʊt/|phr.被锁在外",
"The door won't open, could maintenance come up?|门打不开，能叫维修上来吗？|travel|应急/报修|long|maintenance|/ˈmeɪntənəns/|n.维修",
"My flight got canceled, what are my options?|我的航班取消了，我有什么选择？|travel|应急/改签|long|option|/ˈɑpʃən/|n.选择",
"Could you rebook me on the earliest flight?|能帮我改到最早的航班吗？|travel|应急/改签|long|rebook|/ˌriːˈbʊk/|v.重新预订",
"Does the airline provide accommodation for the delay?|延误期间航空公司提供住宿吗？|travel|应急/延误|long|accommodation|/əˌkɑməˈdeɪʃən/|n.住宿",
"Where can I wait for the rebooked flight?|我在哪儿等改签的航班？|travel|应急/等待|short|wait|/weɪt/|v.等待",
"Is there a lounge I can access with my ticket?|凭我的票能进休息室吗？|travel|机场/服务|long|lounge|/laʊndʒ/|n.休息室",
"Where can I print my boarding pass?|我在哪儿能打印登机牌？|travel|机场/值机|short|print|/prɪnt/|v.打印",
"My carry-on is slightly over the limit, is that okay?|我的登机箱略超限，可以吗？|travel|机场/行李|long|carry-on|/ˈkæri ɔn/|n.登机行李",
"Can I bring this cake through security?|这块蛋糕能过安检吗？|travel|机场/安检|short|security|/sɪˈkjʊrəti/|n.安检",
"Do I need to remove my belt at security?|过安检要解皮带吗？|travel|机场/安检|long|belt|/bɛlt/|n.腰带",
"Where's the priority lane for boarding?|优先登机通道在哪儿？|travel|机场/登机|short|priority lane|/praɪˈɔrəti leɪn/|phr.优先通道",
"Are there any duty-free shops past security?|安检后有免税店吗？|travel|机场/免税|long|duty-free|/ˈduːti friː/|adj.免税的",
"How much perfume can I bring back duty-free?|免税能带多少香水回来？|travel|机场/免税|short|perfume|/pɜrˈfjuːm/|n.香水",
"Could you keep my passport in the room safe?|你把护照放房间保险箱里保管吧。|travel|酒店/安全|long|safe|/seɪf/|n.保险箱",
]
