# -*- coding: utf-8 -*-
# 语料池 2/5：旅游 · 购物/观光/货币/应急/网络（接续池1）
RAW = [
"How much does this cost in total?|这个总共多少钱？|travel|购物/问价|short|in total|/ɪn ˈtoʊtəl/|phr.总共",
"Is this on sale at the moment?|这个现在打折吗？|travel|购物/问价|short|on sale|/ɑn seɪl/|phr.打折出售",
"Do you have this shirt in a medium?|这件衬衫有中号吗？|travel|购物/尺码|short|medium|/ˈmiːdiəm/|n.中号",
"Could I try these shoes on in a nine?|这双鞋能拿九号给我试试吗？|travel|购物/试穿|long|try on|/traɪ ɑn/|phr.试穿",
"Where are the fitting rooms, please?|请问试衣间在哪儿？|travel|购物/试穿|short|fitting room|/ˈfɪtɪŋ ruːm/|phr.试衣间",
"It's a bit tight around the shoulders.|肩部有点紧。|travel|购物/试穿|short|tight|/taɪt/|adj.紧的",
"Do you have it in any other colors?|这个有其他颜色吗？|travel|购物/颜色|short|color|/ˈkʌlər/|n.颜色",
"This one suits you really well.|这个真的很衬你。|travel|购物/夸赞|short|suit|/suːt/|v.适合",
"Could you give me a better price if I buy two?|我买两个能便宜点吗？|travel|购物/议价|long|better price|/ˈbɛtər praɪs/|phr.更优惠的价格",
"That's a bit over my budget, honestly.|说实话这有点超出我的预算了。|travel|购物/议价|long|budget|/ˈbʌdʒɪt/|n.预算",
"Can I pay by card or is it cash only?|能刷卡还是只能现金？|travel|购物/支付|short|by card|/baɪ kɑrd/|phr.刷卡",
"Do you take mobile payment like Alipay?|你们收支付宝这类手机支付吗？|travel|购物/支付|long|mobile payment|/ˈmoʊbəl ˈpeɪmənt/|phr.移动支付",
"Could I get a tax refund form for this?|这个能给我开退税单吗？|travel|购物/退税|short|tax refund|/tæks ˈriːfʌnd/|phr.退税",
"I'd like to return this jacket with the receipt.|我想凭收据退这件夹克。|travel|购物/退换|long|return|/rɪˈtɜːrn/|v.退回",
"Could I exchange it for a larger size instead?|能换一个大一号的吗？|travel|购物/退换|short|exchange|/ɪksˈtʃeɪndʒ/|v.调换",
"It has a small scratch on the back.|背面有一道小划痕。|travel|购物/退换|short|scratch|/skrætʃ/|n.划痕",
"Are these souvenirs handmade locally?|这些纪念品是本地手工做的吗？|travel|购物/纪念品|short|handmade|/ˌhændˈmeɪd/|adj.手工的",
"Could you wrap it as a gift, please?|能帮我按礼物包装一下吗？|travel|购物/包装|short|wrap|/ræp/|v.包装",
"Is this shop open on Sunday mornings?|这家店周日上午开门吗？|travel|购物/营业|short|open|/ˈoʊpən/|adj.营业的",
"What time do you close today?|今天几点关门？|travel|购物/营业|short|close|/kloʊz/|v.关门",
"Where can I buy tickets for the castle?|城堡的票在哪儿买？|travel|观光/门票|short|castle|/ˈkæsəl/|n.城堡",
"Is there a student discount on the entrance ticket?|门票有学生优惠吗？|travel|观光/门票|long|entrance|/ˈɛntrəns/|n.入场",
"Are children under six free of charge?|六岁以下儿童免费吗？|travel|观光/门票|short|free of charge|/fri əv tʃɑrdʒ/|phr.免费",
"Could you take a photo of us with this view?|能帮我们以这个景为背景拍张照吗？|travel|观光/拍照|long|photo|/ˈfoʊtoʊ/|n.照片",
"Excuse me, could you take a picture for us?|打扰一下，能帮我们拍张照吗？|travel|观光/拍照|short|picture|/ˈpɪktʃər/|n.照片",
"Is it okay if I take photos inside?|里面可以拍照吗？|travel|观光/拍照|short|inside|/ˌɪnˈsaɪd/|adv.在里面",
"Could you use portrait mode for this one?|这张能用人像模式拍吗？|travel|观光/拍照|short|portrait|/ˈpɔːrtrət/|n.肖像",
"How long does the guided tour take?|带讲解的游览大概多久？|travel|观光/导览|short|guided tour|/ˈɡaɪdɪd tʊr/|phr.导览游",
"Does the audio guide come in Chinese?|语音导览有中文的吗？|travel|观光/导览|short|audio guide|/ˈɔːdioʊ ɡaɪd/|phr.语音导览",
"When is the next tour starting?|下一场导览什么时候开始？|travel|观光/导览|short|tour|/tʊr/|n.游览",
"Is the observation deck open on rainy days?|观景台雨天开放吗？|travel|观光/开放|long|observation deck|/ˌɑbzərˈveɪʃən dɛk/|phr.观景台",
"What are the opening hours in winter?|冬天开放时间是几点到几点？|travel|观光/开放|short|opening hours|/ˈoʊpənɪŋ ˈaʊərz/|phr.开放时间",
"Is the museum closed on Mondays?|博物馆周一闭馆吗？|travel|观光/开放|short|closed|/kloʊzd/|adj.关闭的",
"Where's the best spot to watch the sunset?|看日落最好的位置在哪儿？|travel|观光/景点|long|sunset|/ˈsʌnsɛt/|n.日落",
"Is the hot spring open to day visitors?|温泉对当天游客开放吗？|travel|观光/景点|short|day visitor|/deɪ ˈvɪzɪtər/|phr.一日游客",
"Can I get a map of the hiking trails?|能给我一份徒步路线图吗？|travel|观光/徒步|short|trail|/treɪl/|n.小径",
"Is the cable car running in this weather?|这种天气缆车还运行吗？|travel|观光/缆车|short|cable car|/ˈkeɪbəl kɑːr/|phr.缆车",
"Where can I exchange some US dollars?|我在哪儿能换些美元？|travel|货币/兑换|short|exchange|/ɪksˈtʃeɪndʒ/|v.兑换",
"What's the exchange rate today?|今天的汇率是多少？|travel|货币/兑换|short|exchange rate|/ɪksˈtʃeɪndʒ reɪt/|phr.汇率",
"Could you break this hundred into smaller bills?|能把这张一百换成零钱吗？|travel|货币/换零|long|break|/breɪk/|v.兑换开",
"Where's the nearest ATM that takes foreign cards?|最近的能刷外卡的取款机在哪儿？|travel|银行/取现|long|ATM|/ˌeɪ tiː ˈɛm/|n.自动取款机",
"Is there a daily limit on withdrawals?|取现有每日限额吗？|travel|银行/取现|short|withdrawal|/wɪðˈdrɔːəl/|n.取款",
"I'd like to send this parcel to China, please.|我想把这个包裹寄到中国。|travel|邮政/寄件|short|parcel|/ˈpɑːrsəl/|n.包裹",
"How much is the postage for this letter by air?|这封信走航空邮资多少？|travel|邮政/寄件|long|postage|/ˈpoʊstɪdʒ/|n.邮资",
"Could I get a tracking number for the package?|包裹能给我个单号吗？|travel|邮政/寄件|long|tracking number|/ˈtrækɪŋ ˈnʌmbər/|phr.快递单号",
"Do you sell stamps and envelopes here?|这里卖邮票和信封吗？|travel|邮政/购买|short|stamp|/stæmp/|n.邮票",
"I don't feel well and need to see a doctor.|我不舒服，需要看医生。|travel|应急/就医|short|see a doctor|/si ə ˈdɑktər/|phr.看医生",
"Is there a pharmacy nearby that's open now?|附近有现在还营业的药店吗？|travel|应急/药店|short|pharmacy|/ˈfɑːrməsi/|n.药店",
"Could you give me something for a headache?|能给我点治头痛的药吗？|travel|应急/药店|short|headache|/ˈhɛdeɪk/|n.头痛",
"I've been having a sore throat since yesterday.|我从昨天起嗓子一直疼。|travel|应急/症状|short|sore throat|/sɔr θroʊt/|phr.喉咙痛",
"My stomach hurts and I feel dizzy.|我胃疼还头晕。|travel|应急/症状|short|dizzy|/ˈdɪzi/|adj.头晕的",
"Where is the nearest emergency room?|最近的急诊室在哪儿？|travel|应急/就医|short|emergency room|/ɪˈmɜːrdʒənsi ruːm/|phr.急诊室",
"Call an ambulance, please!|请叫救护车！|travel|应急/急救|short|ambulance|/ˈæmbjələns/|n.救护车",
"I need to report a stolen wallet.|我要报失一个被偷的钱包。|travel|应急/遗失|short|stolen|/ˈstoʊlən/|adj.被偷的",
"Where's the nearest police station?|最近的警察局在哪儿？|travel|应急/报警|short|police station|/pəˈlis ˈsteɪʃən/|phr.警察局",
"My phone was lost on the subway.|我的手机在地铁上丢了。|travel|应急/遗失|short|lost|/lɔːst/|adj.丢失的",
"Could you help me contact the lost and found?|能帮我联系一下失物招领处吗？|travel|应急/遗失|long|lost and found|/lɔst ənd faʊnd/|phr.失物招领",
"I left my passport in the taxi.|我把护照落在出租车上了。|travel|应急/遗失|short|leave|/liːv/|v.落下",
"Do I need to reapply for a new visa if the passport is lost?|护照丢了的话我需要重新申请签证吗？|travel|应急/补办|long|reapply|/ˌriːəˈplaɪ/|v.重新申请",
"Where's my country's consulate in this city?|我们国家的领事馆在这个城市的哪儿？|travel|应急/求助|long|consulate|/ˈkɑnsələt/|n.领事馆",
"Watch out for the pickpockets in this area.|这一带要小心扒手。|travel|应急/安全|short|pickpocket|/ˈpɪkpɑːkɪt/|n.扒手",
"Is this neighborhood safe to walk at night?|这一带晚上走路安全吗？|travel|应急/安全|long|neighborhood|/ˈneɪbərhʊd/|n.街区",
"Could you keep an eye on my bag for a second?|能帮我看一下包吗，就一小会儿？|travel|应急/求助|long|keep an eye on|/kip ən aɪ ɑn/|phr.照看",
"Does anyone here speak Chinese?|这里有会说中文的人吗？|travel|沟通/求助|short|anyone|/ˈɛniwʌn/|pron.任何人",
"Could you speak a bit more slowly, please?|能说慢一点吗？|travel|沟通/语速|short|slowly|/ˈsloʊli/|adv.慢慢地",
"How do you say this in English?|这个用英语怎么说？|travel|沟通/请教|short|say|/seɪ/|v.说",
"Could you write it down for me, please?|能帮我写下来吗？|travel|沟通/记录|short|write down|/raɪt daʊn/|phr.写下",
"Sorry, I still didn't catch that.|抱歉，我还是没听清。|travel|沟通/没听清|short|catch|/kætʃ/|v.听清",
"Is there free Wi-Fi in this cafe?|这家咖啡馆有免费Wi-Fi吗？|travel|网络/连接|short|Wi-Fi|/ˈwaɪfaɪ/|n.无线网络",
"What's the password for the Wi-Fi here?|这里的Wi-Fi密码是多少？|travel|网络/连接|short|password|/ˈpæswɜːrd/|n.密码",
"Where can I buy a local SIM card?|我在哪儿能买到本地电话卡？|travel|网络/电话卡|short|SIM card|/ˈsɪm kɑrd/|phr.电话卡",
"My phone has no signal here.|我的手机在这儿没信号。|travel|网络/信号|short|signal|/ˈsɪɡnəl/|n.信号",
"Could I borrow your charger for a moment?|能借用一下你的充电器吗？|travel|网络/充电|short|charger|/ˈtʃɑːrdʒər/|n.充电器",
"Is there a power socket near this seat?|这个座位附近有电源插座吗？|travel|网络/充电|short|socket|/ˈsɑːkɪt/|n.插座",
"Looks like rain, should we bring umbrellas?|看起来要下雨，要带伞吗？|travel|天气/出行|short|umbrella|/ʌmˈbrɛlə/|n.雨伞",
"The forecast says it will clear up tomorrow.|预报说明天放晴。|travel|天气/预报|short|forecast|/ˈfɔːrkæst/|n.预报",
"It's boiling hot outside today.|今天外面热死了。|travel|天气/描述|short|boiling|/ˈbɔɪlɪŋ/|adj.酷热的",
"Bundle up, it's freezing out there.|多穿点，外面冷得要命。|travel|天气/描述|short|freezing|/ˈfriːzɪŋ/|adj.极冷的",
"Is the fog going to affect the ferry schedule?|雾会影响渡轮班次吗？|travel|天气/出行|long|ferry|/ˈfɛri/|n.渡轮",
"I'd like a one-way ticket to Osaka, please.|请给我一张去大阪的单程票。|travel|交通/购票|short|one-way|/ˈwʌnweɪ/|adj.单程的",
"When is the next ferry to the island?|下一班去岛上的渡轮是几点？|travel|交通/轮渡|short|ferry|/ˈfɛri/|n.渡轮",
"How long does the boat ride take?|坐船要多久？|travel|交通/轮渡|short|boat ride|/boʊt raɪd/|phr.乘船",
"Is there a night bus to the airport?|有去机场的夜班车吗？|travel|交通/公交|short|night bus|/naɪt bʌs/|phr.夜班公交",
"Where's the pickup point for the airport shuttle?|机场班车的乘车点在哪儿？|travel|交通/班车|long|shuttle|/ˈʃʌtəl/|n.班车",
"Could you tell me when we get to the last stop?|到终点站时能告诉我一声吗？|travel|交通/乘车|long|last stop|/læst stɑp/|phr.终点站",
"Is this the right platform for the airport express?|机场快线是在这个站台坐吗？|travel|交通/火车|long|express|/ɪkˈsprɛs/|n.快车",
"Are there any seats available on the earlier train?|早一点的那趟车还有座吗？|travel|交通/火车|long|available|/əˈveɪləbəl/|adj.有余票的",
"Could you help me carry this bag upstairs?|能帮我把这个包搬上楼吗？|travel|请求/搬运|short|carry|/ˈkæri/|v.搬运",
"Would you mind taking a photo with me?|你介意和我合个影吗？|travel|社交/合影|short|photo|/ˈfoʊtoʊ/|n.照片",
"Excuse me, is this seat free?|打扰一下，这个座位空着吗？|travel|交通/乘车|short|free|/friː/|adj.空着的",
"Sorry to bother you, but is this your bag?|抱歉打扰，这是您的包吗？|travel|沟通/确认|long|bother|/ˈbɑðər/|v.打扰",
"Could you keep the noise down a little?|能小点声吗？|travel|公共/提醒|short|noise|/nɔɪz/|n.噪音",
"Is this the queue for tickets?|这是买票的队伍吗？|travel|公共/排队|short|queue|/kjuː/|n.队列",
"Excuse me, may I get past?|打扰一下，能让一下吗？|travel|公共/借过|short|get past|/ɡɛt pæst/|phr.通过",
"Where can I find a public restroom?|公共卫生间在哪儿？|travel|公共/便民|short|restroom|/ˈrɛstruːm/|n.卫生间",
"Is the tap water safe to drink here?|这里的自来水能直接喝吗？|travel|生活/饮水|short|tap water|/tæp ˈwɔːtər/|phr.自来水",
"Could you recommend a less crowded time to visit?|能推荐个人少点的参观时间吗？|travel|观光/建议|long|crowded|/ˈkraʊdɪd/|adj.拥挤的",
"Are there any local festivals on this weekend?|这周末有什么本地节日活动吗？|travel|观光/活动|long|festival|/ˈfɛstəvəl/|n.节日",
"Where do locals usually hang out at night?|本地人晚上一般去哪儿玩？|travel|观光/建议|long|hang out|/hæŋ aʊt/|phr.消磨时光",
"Is it worth buying the city pass?|城市通票值得买吗？|travel|观光/门票|short|city pass|/ˈsɪti pæs/|phr.城市通票",
"Could I get a map with the bus routes marked?|能给我一份标了公交线路的地图吗？|travel|问路/地图|long|marked|/mɑrkt/|adj.标注的",
]
