# -*- coding: utf-8 -*-
# 语料池 6/7：日常 · 生活服务/数码/通勤/学习（ids 补充）
RAW = [
"I'd like to open a savings account, please.|我想开一个储蓄账户。|daily|银行/开户|short|savings account|/ˈseɪvɪŋz əˈkaʊnt/|phr.储蓄账户",
"Could you tell me my account balance?|能查一下我的账户余额吗？|daily|银行/查询|short|balance|/ˈbæləns/|n.余额",
"I'd like to transfer some money to this account.|我想往这个账户转点钱。|daily|银行/转账|long|transfer|/trænsˈfɜːr/|v.转账",
"Is there a fee for using this card abroad?|在国外用这张卡有手续费吗？|daily|银行/费用|long|abroad|/əˈbrɔːd/|adv.在国外",
"Could you help me check why my card was declined?|能帮我看看卡为什么刷不了吗？|daily|银行/故障|long|declined|/dɪˈklaɪnd/|v.被拒(pp.)",
"I'd like to withdraw five hundred from my account.|我想从账户取五百。|daily|银行/取现|long|withdraw|/wɪðˈdrɔː/|v.取款",
"I have an appointment for a haircut at three.|我三点约了理发。|daily|理发/预约|short|haircut|/ˈhɛrkʌt/|n.理发",
"Just a trim please, don't cut it too short.|稍微修一下就行，别剪太短。|daily|理发/要求|long|trim|/trɪm/|n.修剪",
"Could you thin it out a bit at the back?|后脑勺能打薄一点吗？|daily|理发/要求|short|thin out|/θɪn aʊt/|phr.打薄",
"I'd like the same style as last time, please.|还是照上次那个发型剪。|daily|理发/要求|long|style|/staɪl/|n.发型",
"My phone screen got cracked this morning.|我手机屏幕今早摔裂了。|daily|手机/维修|short|cracked|/krækt/|adj.裂的",
"How long would the repair take?|维修大概要多久？|daily|维修/咨询|short|repair|/rɪˈpɛr/|n.维修",
"Could you take a look at my laptop? It won't start.|能看看我的笔记本电脑吗？开不了机。|daily|维修/求助|long|start|/stɑrt/|v.启动",
"Is it still under warranty?|还在保修期内吗？|daily|维修/保修|short|warranty|/ˈwɔrənti/|n.保修",
"The Wi-Fi keeps dropping every few minutes.|Wi-Fi每隔几分钟就断一次。|daily|网络/故障|long|drop|/drɑp/|v.断开",
"Could you share the Wi-Fi password with me?|能把Wi-Fi密码分享给我吗？|daily|网络/连接|long|share|/ʃɛr/|v.分享",
"My phone storage is almost full.|我手机存储快满了。|daily|手机/存储|short|storage|/ˈstɔrɪdʒ/|n.存储",
"Could you send me the link to that article?|能把那篇文章的链接发我吗？|daily|网络/分享|long|link|/lɪŋk/|n.链接",
"I'll share my location with you right now.|我现在把位置分享给你。|daily|手机/定位|short|location|/loʊˈkeɪʃən/|n.位置",
"The video call keeps freezing on my end.|我这边的视频通话一直卡。|daily|网络/视频|short|freeze|/friz/|v.卡住",
"Could you scan this QR code for me?|能帮我扫一下这个二维码吗？|daily|手机/扫码|short|scan|/skæn/|v.扫描",
"I take the subway to work every day.|我每天坐地铁上班。|daily|通勤/方式|short|subway|/ˈsʌbweɪ/|n.地铁",
"The morning rush hour is unbearable sometimes.|早高峰有时候真让人受不了。|daily|通勤/高峰|long|rush hour|/rʌʃ ˈaʊər/|phr.高峰时段",
"I usually cycle to work when the weather is good.|天气好的时候我一般骑车上班。|daily|通勤/骑行|long|cycle|/ˈsaɪkəl/|v.骑车",
"How long is your commute in the morning?|你早上通勤要多久？|daily|通勤/时长|short|commute|/kəˈmjuːt/|n.通勤",
"I got stuck in traffic for over an hour this morning.|我今早堵车堵了一个多小时。|daily|通勤/堵车|long|stuck|/stʌk/|adj.堵住的",
"There was a signal failure on my line today.|今天我们那条线信号故障了。|daily|通勤/故障|long|failure|/ˈfeɪljər/|n.故障",
"I work from home on Wednesdays and Fridays.|我周三周五在家办公。|daily|通勤/居家办公|long|work from home|/wɜrk frʌm hoʊm/|phr.居家办公",
"Let's carpool to save on gas money.|咱们拼车省点油钱吧。|daily|通勤/拼车|short|carpool|/ˈkɑrpuːl/|v.拼车",
"Is there a bike-sharing station near your office?|你们公司附近有共享单车停放点吗？|daily|通勤/骑行|long|bike-sharing|/baɪk ˈʃɛrɪŋ/|phr.共享单车",
"Don't forget to tap out when you exit the station.|出站别忘了刷卡。|daily|通勤/刷卡|long|tap out|/tæp aʊt/|phr.刷卡出站",
"How often do you go to the gym in a week?|你一周去几次健身房？|daily|频率/询问|short|how often|/haʊ ˈɔfən/|phr.多久一次",
"I rarely stay up past midnight these days.|我这阵子很少过了半夜才睡。|daily|频率/描述|short|rarely|/ˈrɛrli/|adv.很少",
"She drops by our place every now and then.|她偶尔来我们家坐坐。|daily|频率/描述|short|every now and then|/ˈɛvri naʊ ənd ðɛn/|phr.时不时",
"We usually have dinner together on Sundays.|我们通常周日一起吃晚饭。|daily|频率/习惯|short|usually|/ˈjuːʒuəli/|adv.通常",
"I've been studying Japanese on and off for years.|我断断续续学了好几年日语。|daily|频率/描述|long|on and off|/ɑn ənd ɔf/|phr.断断续续",
"Hardly a day goes by without checking my email.|几乎没有一天不查邮箱。|daily|频率/描述|long|hardly|/ˈhɑrdli/|adv.几乎不",
"From time to time I treat myself to a nice dinner.|我时不时犒劳自己一顿大餐。|daily|频率/习惯|long|treat|/triːt/|v.款待",
"Could you recommend some podcasts for learners?|能推荐几个适合学习者的播客吗？|daily|学习/资源|long|podcast|/ˈpɑdkæst/|n.播客",
"I've finished three books so far this year.|我今年到目前为止读完了三本书。|daily|学习/进度|short|so far|/soʊ fɑr/|phr.到目前为止",
"Watching shows with subtitles helps me a lot.|看带字幕的剧对我帮助很大。|daily|学习/方法|short|subtitle|/ˈsʌbtaɪtəl/|n.字幕",
"I keep a diary in English every evening.|我每晚用英语写日记。|daily|学习/习惯|short|diary|/ˈdaɪəri/|n.日记",
"Speaking is the hardest part for me by far.|口语到目前为止是我最难的部分。|daily|学习/难点|short|by far|/baɪ fɑr/|phr.显然最",
"I signed up for an online course last month.|我上个月报了一门网课。|daily|学习/课程|short|sign up|/saɪn ʌp/|phr.报名",
"It took me ages to finish that registration form.|那张登记表我填了好半天。|daily|事务/表格|long|ages|/ˈeɪdʒɪz/|n.很长时间",
"Do I need to make an appointment for the visa office?|去签证处需要预约吗？|daily|事务/预约|long|make an appointment|/meɪk ən əˈpɔɪntmənt/|phr.预约",
"Which window should I go to for certificate pickup?|领证明应该去几号窗口？|daily|事务/办理|long|window|/ˈwɪndoʊ/|n.窗口",
"The office is closed during the lunch break.|午休时间办事处不办公。|daily|事务/营业|short|lunch break|/lʌntʃ breɪk/|phr.午休",
"You need to bring copies of all the documents.|所有文件都要带复印件。|daily|事务/材料|short|copy|/ˈkɑpi/|n.复印件",
"Could you sign here and print your name below?|能在这里签名并在下面写正楷姓名吗？|daily|事务/签字|long|print|/prɪnt/|v.用印刷体写",
"When will the results be announced?|结果什么时候公布？|daily|事务/查询|short|announce|/əˈnaʊns/|v.公布",
"Is there anything else I need to do after this?|这之后我还有别的要办的吗？|daily|事务/确认|long|else|/ɛls/|adj.其他的",
"Sorry, could you repeat the last part?|抱歉，能重复下最后那部分吗？|daily|沟通/确认|short|repeat|/rɪˈpiːt/|v.重复",
"Just to confirm, we're meeting at six, right?|确认一下，咱们六点见，对吧？|daily|沟通/确认|short|confirm|/kənˈfɜrm/|v.确认",
"Let me make sure I've got this right.|让我确认一下我理解对了。|daily|沟通/复述|short|make sure|/meɪk ʃʊr/|phr.确认",
"So what you're saying is it's too late to change?|你的意思是现在改已经来不及了？|daily|沟通/复述|long|what you're saying|/wʌt jʊr ˈseɪɪŋ/|phr.你所说的话",
"In other words, we have to start over.|也就是说，我们得从头再来。|daily|沟通/总结|short|in other words|/ɪn ˈʌðər wɜrdz/|phr.换句话说",
"Let me put it this way: we need more time.|这么说吧：我们需要更多时间。|daily|沟通/解释|long|put it this way|/pʊt ɪt ðɪs weɪ/|phr.这么说",
"What I mean is we should wait a bit longer.|我的意思是我们应该再等等。|daily|沟通/澄清|long|mean|/miːn/|v.意指",
"Sorry, that came out wrong, let me start over.|抱歉说错了，我重新说。|daily|沟通/纠正|long|come out|/kʌm aʊt/|phr.说出口",
"How do you spell your surname?|您的姓怎么拼？|daily|沟通/拼写|short|spell|/spɛl/|v.拼写",
"Is it okay to say it like that?|像那样说可以吗？|daily|沟通/求证|short|okay|/oʊˈkeɪ/|adj.可以的",
"Am I making myself clear?|我说清楚了吗？|daily|沟通/确认|short|clear|/klɪr/|adj.清楚的",
"Let me get this straight once and for all.|让我把这事彻底弄清楚。|daily|沟通/理清|long|once and for all|/wʌns ənd fɔr ɔl/|phr.一劳永逸地",
"Pardon me for asking, but how old are you?|恕我冒昧，你多大了？|daily|提问/礼貌|short|pardon|/ˈpɑrdən/|v.原谅",
"Would you mind if I asked a personal question?|介意我问个私人问题吗？|daily|提问/礼貌|long|personal|/ˈpɜrsənəl/|adj.私人的",
"Do you happen to know if the store opens today?|你碰巧知道那家店今天开不开门吗？|daily|提问/打听|long|happen to|/ˈhæpən tuː/|phr.碰巧",
"I was wondering whether you could help me out.|不知你能否帮我个忙。|daily|提问/委婉|long|wonder|/ˈwʌndər/|v.想知道",
"Could you possibly work this weekend instead?|你这周末能不能来加班？|daily|提问/请求|long|possibly|/ˈpɑsəbli/|adv.可能地",
"Is there any chance you could come earlier?|你有没有可能早点来？|daily|提问/请求|short|any chance|/ˈɛni tʃæns/|phr.有可能",
"Would it be all right if I left early today?|我今天早点走可以吗？|daily|提问/许可|long|all right|/ɔl raɪt/|adj.可以",
"I was hoping you could stay for dinner.|我本希望你能留下来吃晚饭。|daily|邀请/委婉|short|hope|/hoʊp/|v.希望",
"I'd rather not talk about it right now.|我现在宁愿不谈这个。|daily|拒绝/委婉|short|would rather not|/wʊd ˈræðər nɑt/|phr.宁愿不",
"That's very kind, but I'll manage on my own.|你真好，不过我自己能行。|daily|拒绝/委婉|long|manage|/ˈmænɪdʒ/|v.应付",
"Thanks for asking, but I've got plans tonight.|谢谢邀请，但我今晚有安排了。|daily|拒绝/委婉|long|got plans|/ɡɑt plænz/|phr.有安排",
"Maybe next time, okay?|下次吧，行吗？|daily|拒绝/缓和|short|next time|/nɛkst taɪm/|phr.下次",
"Let me think it over before I decide.|决定之前让我考虑一下。|daily|犹豫/拖延|short|think over|/θɪŋk ˈoʊvər/|phr.仔细考虑",
"I'm afraid I have other commitments this weekend.|这周末我恐怕另有安排。|daily|拒绝/委婉|long|commitment|/kəˈmɪtmənt/|n.既定安排",
"I'll think about it and let you know tomorrow.|我考虑一下，明天给你答复。|daily|犹豫/答复|short|let know|/lɛt noʊ/|phr.告知",
"Can I get back to you on that later?|这事我能稍后再答复你吗？|daily|犹豫/答复|short|get back to|/ɡɛt bæk tuː/|phr.稍后答复",
"I need to check with my wife before I commit.|答应之前我得先跟老婆商量。|daily|犹豫/商量|long|commit|/kəˈmɪt/|v.承诺",
"Where does this bus end up at the last stop?|这趟公交终点站是到哪儿？|daily|出行/咨询|short|end up|/ɛnd ʌp/|phr.最终到达",
"Which line should I switch to for the stadium?|去体育场应该在哪儿换乘？|daily|出行/换乘|short|switch|/swɪtʃ/|v.换乘",
"Could you tell me which stop is next?|能告诉我下一站是哪站吗？|daily|出行/咨询|short|next|/nɛkst/|adj.下一个",
"Is this the right bus for the night market?|去夜市是坐这趟公交吗？|daily|出行/确认|short|night market|/naɪt ˈmɑrkɪt/|phr.夜市",
"I always get off one stop too early.|我总是早下了一站。|daily|出行/失误|short|get off|/ɡɛt ɔːf/|phr.下车",
"Mind the gap between the train and the platform.|小心列车与站台的间隙。|daily|出行/提醒|long|gap|/ɡæp/|n.间隙",
"Stand behind the yellow line, please.|请站在黄线后面。|daily|出行/提醒|short|yellow line|/ˈjɛloʊ laɪn/|phr.黄线",
"Let me grab my keys and we can head out.|我拿上钥匙咱们就能出发。|daily|出行/准备|short|grab|/ɡræb/|v.拿取",
"Are we all set to leave now?|咱们现在可以出发了吗？|daily|出行/确认|short|all set|/ɔl sɛt/|phr.准备就绪",
"Do you have everything you need for the trip?|旅行要带的东西都齐了吗？|daily|出行/确认|long|trip|/trɪp/|n.旅行",
"Remember to bring sunscreen for the beach.|记得带防晒霜去海边。|daily|出行/提醒|short|sunscreen|/ˈsʌnskriːn/|n.防晒霜",
"Let's hit the road before the traffic builds up.|趁还没堵车咱们上路吧。|daily|出行/时间|long|hit the road|/hɪt ðə roʊd/|phr.上路",
"We're halfway there already.|我们已经到一半路程了。|daily|出行/进度|short|halfway|/ˈhæfweɪ/|adv.半途",
"How much longer till we get there?|还有多久才到？|daily|出行/时长|short|how much longer|/haʊ mʌtʃ ˈlɔŋɡər/|phr.还有多久",
"Can we pull over for a quick break?|能靠边停一下歇会儿吗？|daily|出行/休息|short|pull over|/pʊl ˈoʊvər/|phr.靠边停车",
"Watch out! There's a cyclist on your right.|小心！你右边有个骑车的。|daily|出行/提醒|short|cyclist|/ˈsaɪklɪst/|n.骑行者",
"The navigation says we should turn left ahead.|导航说前方应该左转。|daily|出行/导航|long|navigation|/ˌnævɪˈɡeɪʃən/|n.导航",
"We just missed our exit, take the next one.|我们刚错过出口了，走下一个。|daily|出行/失误|long|exit|/ˈɛɡzɪt/|n.出口",
"Is there a parking spot anywhere near here?|这附近有车位吗？|daily|出行/停车|short|parking spot|/ˈpɑrkɪŋ spɑt/|phr.车位",
"I'll drop you off at the corner and find parking.|我在街角放你下，去找车位。|daily|出行/安排|long|corner|/ˈkɔrnər/|n.街角",
"Let's split the gas money after the trip.|行程结束后咱们均摊油费吧。|daily|出行/费用|short|split|/splɪt/|v.分摊",
"Could you keep the receipt for the parking fee?|停车费的收据能留着吗？|daily|出行/凭证|long|parking fee|/ˈpɑrkɪŋ fiː/|phr.停车费",
]
