# -*- coding: utf-8 -*-
# 语料池 9/9：补充收尾（凑满 900）
RAW = [
"Could you grab the door for me?|能帮我扶一下门吗？|daily|请求/帮忙|short|grab|/ɡræb/|v.抓取",
"Let me know when you're on your way.|你出发时跟我说一声。|daily|时间/通知|short|on your way|/ɑn jʊr weɪ/|phr.在路上",
"I'm on my way now, see you soon.|我这就出发，一会儿见。|daily|时间/出发|short|on one's way|/ɑn wʌnz weɪ/|phr.在途中",
"Sorry, something urgent came up at work.|抱歉，工作上有急事。|daily|变故/说明|short|come up|/kʌm ʌp/|phr.突然发生",
"Can we reschedule our meeting to next week?|能把会改到下周吗？|daily|变故/改期|short|reschedule|/ˌriːˈskɛdʒuːl/|v.改期",
"I completely forgot about our appointment.|我把咱们的约见全忘了。|daily|变故/道歉|short|completely|/kəmˈpliːtli/|adv.完全地",
"Sorry for the short notice, but can you come today?|抱歉这么仓促，你今天能来吗？|daily|变故/临时|long|short notice|/ʃɔrt ˈnoʊtɪs/|phr.临时通知",
"Let's play it by ear and see how it goes.|咱们见机行事吧。|daily|计划/灵活|short|play by ear|/pleɪ baɪ ɪr/|phr.随机应变",
"We'll figure something out, don't worry.|我们会想出办法的，别担心。|daily|计划/安抚|short|figure out|/ˈfɪɡjər aʊt/|phr.想出",
"Let's touch base again after the weekend.|周末结束后咱们再碰头。|daily|计划/沟通|short|touch base|/tʌtʃ beɪs/|phr.碰头",
"Keep me in the loop about any changes.|有任何变动随时告诉我。|daily|计划/通知|short|in the loop|/ɪn ðə luːp/|phr.知情的",
"That's settled then, see you Friday.|那就这么定了，周五见。|daily|计划/确认|short|settled|/ˈsɛtld/|adj.定下来的",
"Is everything ready for tomorrow's event?|明天的活动都准备好了吗？|daily|计划/确认|short|event|/ɪˈvɛnt/|n.活动",
"Who's in charge of the arrangements this time?|这次谁负责安排？|daily|分工/询问|short|in charge of|/ɪn tʃɑrdʒ əv/|phr.负责",
"I'll take care of the food and drinks.|吃的喝的交给我。|daily|分工/承担|short|take care of|/teɪk kɛr əv/|phr.负责处理",
"Could you handle the decorations instead?|装饰这部分你来弄行吗？|daily|分工/请求|short|decoration|/ˌdɛkəˈreɪʃən/|n.装饰",
"Leave it to me, I've got this.|交给我，我能搞定。|daily|分工/承担|short|leave it to me|/liv ɪt tu miː/|phr.交给我",
"We're counting on you for the presentation.|演示就靠你了。|daily|分工/期待|short|count on|/kaʊnt ɑn/|phr.依靠",
"You can count me out of this one.|这次我就不参加了。|daily|分工/退出|short|count out|/kaʊnt aʊt/|phr.不包括",
"Let's divide the work and get started.|咱们分工然后开工吧。|daily|分工/组织|short|divide|/dɪˈvaɪd/|v.划分",
"I'll take the lead on this project.|这个项目我来牵头。|daily|分工/领导|short|take the lead|/teɪk ðə liːd/|phr.牵头",
"Two heads are better than one.|三个臭皮匠顶个诸葛亮。|daily|合作/俗语|short|head|/hɛd/|n.头脑",
"Many hands make light work, after all.|人多好办事嘛。|daily|合作/俗语|short|light work|/laɪt wɜrk/|phr.轻松的活",
"Let's pool our ideas and pick the best one.|咱们集思广益，选最好的点子。|daily|合作/头脑风暴|long|pool|/puːl/|v.汇集",
"Could we brainstorm for five minutes first?|咱们先头脑风暴五分钟行吗？|daily|合作/讨论|short|brainstorm|/ˈbreɪnstɔrm/|v.头脑风暴",
"Let's get the ball rolling on this task.|咱们把这项任务启动起来。|daily|执行/开始|short|get the ball rolling|/ɡɛt ðə bɔl ˈroʊlɪŋ/|phr.开始行动",
"I'm still on task, halfway done actually.|我还在做，其实完成一半了。|daily|执行/进度|short|on task|/ɑn tæsk/|phr.在做正事",
"Let's call it done for today.|今天就做到这儿吧。|daily|执行/收尾|short|call it done|/kɔl ɪt dʌn/|phr.算完成",
"We're making good progress so far.|到目前为止进展顺利。|daily|执行/进度|short|progress|/ˈprɑɡrɛs/|n.进展",
"Let's pick up where we left off yesterday.|咱们从昨天停下的地方继续。|daily|执行/继续|short|leave off|/liv ɔf/|phr.停止处",
"Don't leave it until the last minute.|别拖到最后一刻才做。|daily|执行/提醒|short|last minute|/læst ˈmɪnɪt/|phr.最后一刻",
"I work better under pressure, honestly.|说实话我在压力下效率更高。|daily|执行/风格|short|under pressure|/ˈʌndər ˈprɛʒər/|phr.压力之下",
"Let's wrap up the last few items quickly.|咱们快点把最后几项收尾。|daily|执行/收尾|short|wrap up|/ræp ʌp/|phr.收尾",
"Almost there, just a bit more to go.|就快好了，还差一点。|daily|执行/进度|short|almost there|/ˈɔlmoʊst ðɛr/|phr.快到了",
"We finished ahead of schedule for once.|我们这回居然提前完成了。|daily|执行/成果|short|ahead of schedule|/əˈhɛd əv ˈskɛdʒuːl/|phr.提前",
"Better to do it right than to do it fast.|宁可做对也别图快。|daily|执行/原则|short|right|/raɪt/|adv.正确地",
"Double-check everything before you submit.|提交前把所有东西都核对一遍。|daily|执行/提醒|long|submit|/səbˈmɪt/|v.提交",
"It's the little details that make the difference.|细节决定成败。|daily|执行/原则|long|detail|/ˈdiːteɪl/|n.细节",
"Good things take time, as they say.|好事多磨，常言道。|daily|执行/心态|short|take time|/teɪk taɪm/|phr.需要时间",
"Let's not rush this important decision.|这个重要决定咱们别急。|daily|决策/审慎|short|rush|/rʌʃ/|v.仓促行事",
"Sleep on it and decide in the morning.|睡一觉明早再决定。|daily|决策/缓冲|short|sleep on it|/sliːp ɑn ɪt/|phr.考虑一晚",
"What's the worst that could happen?|最坏能坏到哪儿去？|daily|决策/心态|short|worst|/wɜrst/|adj.最坏的",
"Let's have a backup plan just in case.|咱们备个备用方案以防万一。|daily|决策/预案|short|in case|/ɪn keɪs/|phr.以防万一",
"Would you rather stay in or go out tonight?|今晚你更想宅家还是出门？|daily|选择/询问|long|rather|/ˈræðər/|adv.宁愿",
"Which one would you go for, A or B?|A还是B，你选哪个？|daily|选择/询问|short|go for|/ɡoʊ fɔr/|phr.选择",
"I'm torn between the two options.|这两个选项我难以取舍。|daily|选择/纠结|short|torn|/tɔrn/|adj.纠结的",
"Let's just flip a coin and decide.|咱们干脆抛硬币决定吧。|daily|选择/随机|short|flip a coin|/flɪp ə kɔɪn/|phr.抛硬币",
"It boils down to what matters most to you.|这归根结底取决于你最看重什么。|daily|选择/本质|long|boil down to|/bɔɪl daʊn tuː/|phr.归结为",
"You can't have it both ways, you know.|鱼与熊掌不可兼得，你懂的。|daily|选择/权衡|short|both ways|/boʊθ weɪz/|phr.两方面",
"Let me sleep at least eight hours tonight.|今晚我至少要睡够八小时。|daily|作息/目标|short|at least|/ət liːst/|phr.至少",
"I set two alarms just to be safe.|为保险起见我定了两个闹钟。|daily|作息/起床|short|alarm|/əˈlɑrm/|n.闹钟",
"Try to get some sleep on the plane.|在飞机上尽量睡一会儿。|travel|出行/休息|short|get some sleep|/ɡɛt sʌm sliːp/|phr.睡一会儿",
"I always struggle with jet lag for days.|我的时差总要倒好几天。|travel|出行/时差|short|jet lag|/dʒɛt læɡ/|phr.时差反应",
"Drink lots of water during the flight.|飞行期间多喝水。|travel|出行/健康|short|flight|/flaɪt/|n.航班",
"Stretch your legs during long flights.|长途飞行中活动活动腿。|travel|出行/健康|short|stretch legs|/strɛtʃ lɛɡz/|phr.活动腿脚",
"Let me charge my power bank before the trip.|出发前我把充电宝充满。|travel|出行/准备|long|power bank|/ˈpaʊər bæŋk/|phr.充电宝",
"Download some shows for the long ride.|长途路上提前下几部剧。|travel|出行/娱乐|short|download|/ˈdaʊnloʊd/|v.下载",
"Keep your valuables in the front pocket.|贵重物品放前面口袋里。|travel|出行/安全|short|valuable|/ˈvæljuəbəl/|n.贵重物品",
]
