# -*- coding: utf-8 -*-
# 语料池 7/7：日常 · 社交礼仪/情感/职场/处事补充（收尾）
RAW = [
"Please have a seat, I'll be right with you.|请坐，我马上过来。|daily|礼仪/接待|short|right with you|/raɪt wɪð juː/|phr.马上招呼你",
"Make yourself at home.|别拘束，就当自己家。|daily|礼仪/待客|short|make yourself at home|/meɪk jʊrˈsɛlf ət hoʊm/|phr.别客气",
"Would you like anything to drink?|想喝点什么吗？|daily|礼仪/招待|short|drink|/drɪŋk/|n.饮品",
"Please help yourself to some fruit.|请随便吃点水果。|daily|礼仪/招待|short|fruit|/fruːt/|n.水果",
"Sorry, we're out of coffee at the moment.|抱歉，咖啡这会儿没有了。|daily|待客/说明|short|out of|/aʊt əv/|phr.没有…了",
"It was so kind of you to have us over.|你们请我们过来真是太客气了。|daily|礼仪/致谢|long|have over|/hæv ˈoʊvər/|phr.请来做客",
"I insist, this one is on me.|我坚持，这顿我请。|daily|礼仪/买单|short|insist|/ɪnˈsɪst/|v.坚持",
"Let me get the door for you.|我帮你开门。|daily|礼仪/帮忙|short|door|/dɔr/|n.门",
"After you, please.|您先请。|daily|礼仪/礼让|short|after you|/ˈæftər juː/|phr.您先请",
"Excuse me for a moment, I'll be right back.|失陪一下，我马上回来。|daily|礼仪/离席|long|right back|/raɪt bæk/|phr.马上回来",
"Sorry to cut in, but there's something important.|抱歉打断，但有件要紧事。|daily|礼仪/插话|long|cut in|/kʌt ɪn/|phr.插话",
"Go ahead, I'm listening.|你说吧，我在听。|daily|礼仪/倾听|short|go ahead|/ɡoʊ əˈhɛd/|phr.请讲",
"That's news to me!|这我可是头一回听说！|daily|回应/惊讶|short|news|/nuz/|n.消息",
"You can say that again.|你说得太对了。|daily|回应/赞同|short|say that again|/seɪ ðæt əˈɡɛn/|phr.完全同意",
"Tell me more about it, I'm all ears.|多讲讲呗，我洗耳恭听。|daily|回应/兴趣|long|all ears|/ɔl ɪrz/|phr.洗耳恭听",
"That sounds like a plan.|听起来是个好主意。|daily|回应/赞同|short|sound like|/saʊnd laɪk/|phr.听起来",
"Way to go, you nailed it!|干得漂亮，你搞定了！|daily|夸赞/成就|short|nail|/neɪl/|v.搞定",
"You should be really proud of yourself.|你真该为自己骄傲。|daily|夸赞/肯定|short|proud|/praʊd/|adj.骄傲的",
"I take my hat off to you.|我对你佩服得五体投地。|daily|夸赞/敬佩|short|take one's hat off|/teɪk wʌnz hæt ɔf/|phr.致敬",
"You always know just what to say.|你总是那么会说话。|daily|夸赞/口才|short|know what to say|/noʊ wʌt tu seɪ/|phr.会说话",
"She has a heart of gold.|她心地特别善良。|daily|夸赞/人品|short|heart of gold|/hɑrt əv ɡoʊld/|phr.金子般的心",
"He's the most reliable person I know.|他是我认识的最靠谱的人。|daily|夸赞/人品|long|reliable|/rɪˈlaɪəbəl/|adj.可靠的",
"That took a lot of courage, I admire that.|那需要很大勇气，我很佩服。|daily|夸赞/勇气|long|courage|/ˈkɜrɪdʒ/|n.勇气",
"I'm sorry to hear that, is there anything I can do?|听到这消息我很难过，我能做点什么吗？|daily|安慰/慰问|long|hear|/hɪr/|v.听说",
"Please let me know if you need anything at all.|有任何需要尽管告诉我。|daily|安慰/支持|short|at all|/ət ɔl/|phr.根本(用于强调)",
"My heart goes out to you and your family.|我和你家人一样感同身受。|daily|安慰/慰问|long|go out to|/ɡoʊ aʊt tuː/|phr.同情",
"Stay strong, we're all behind you.|坚强点，我们都支持你。|daily|安慰/支持|short|behind|/bɪˈhaɪnd/|prep.支持",
"It could happen to anyone, don't blame yourself.|谁都可能遇到这种事，别自责。|daily|安慰/宽慰|long|blame|/bleɪm/|v.责怪",
"Look on the bright side, at least nobody got hurt.|往好里想，至少没人受伤。|daily|安慰/宽慰|long|bright side|/braɪt saɪd/|phr.光明面",
"Everything happens for a reason, somehow.|凡事皆有因，冥冥之中自有安排。|daily|安慰/宽慰|short|for a reason|/fər ə ˈriːzən/|phr.有原因的",
"Time heals almost everything, give it a while.|时间几乎能治愈一切，慢慢来。|daily|安慰/宽慰|long|heal|/hiːl/|v.治愈",
"Let's look at it from another angle.|咱们换个角度看这事。|daily|讨论/视角|short|angle|/ˈæŋɡəl/|n.角度",
"Playing devil's advocate here, what if it fails?|我唱个反调，万一失败了呢？|daily|讨论/反方|long|devil's advocate|/ˈdɛvəlz ˈædvəkət/|phr.唱反调的人",
"Let's weigh the pros and cons together.|咱们一起权衡下利弊。|daily|讨论/权衡|short|pros and cons|/proʊz ənd kɑnz/|phr.利弊",
"What are the odds of that actually happening?|那事真发生的概率有多大？|daily|讨论/概率|long|odds|/ɑdz/|n.可能性",
"Let's not jump to conclusions here.|咱们先别急着下结论。|daily|讨论/审慎|short|jump to conclusions|/dʒʌmp tu kənˈkluʒənz/|phr.妄下结论",
"There are two sides to every story.|每件事都有两面。|daily|讨论/客观|short|two sides|/tu saɪdz/|phr.两面",
"Let's agree on the basics before we move on.|继续之前咱们先就基本点达成一致。|daily|讨论/共识|long|basics|/ˈbeɪsɪks/|n.基本要点",
"Could we come back to the main point?|咱们能回到正题上来吗？|daily|讨论/聚焦|short|main point|/meɪn pɔɪnt/|phr.正题",
"That's beside the point we're discussing.|那不是我们正在讨论的重点。|daily|讨论/聚焦|short|beside the point|/bɪˈsaɪd ðə pɔɪnt/|phr.离题",
"Let's put that issue aside for now.|这个问题咱们先放一放。|daily|讨论/搁置|short|put aside|/pʊt əˈsaɪd/|phr.放一边",
"I'd like to add one small point here.|我想在这儿补充一点。|daily|讨论/补充|short|add|/æd/|v.补充",
"Sorry, but I have to disagree on that point.|抱歉，这一点我不得不反对。|daily|讨论/反对|long|disagree|/ˌdɪsəˈɡriː/|v.不同意",
"That's a reasonable concern, actually.|这确实是个合理的顾虑。|daily|讨论/认可|short|reasonable|/ˈrizənəbəl/|adj.合理的",
"Let's find a middle ground we can both accept.|咱们找个双方都能接受的折中方案。|daily|讨论/折中|long|middle ground|/ˈmɪdəl ɡraʊnd/|phr.折中",
"It's a win-win for both of us.|这对咱们俩是双赢。|daily|讨论/合作|short|win-win|/ˈwɪn wɪn/|phr.双赢",
"Could you walk me through the process step by step?|能一步步带我过一遍流程吗？|daily|请教/流程|long|step by step|/stɛp baɪ stɛp/|phr.一步步",
"What do I do if it doesn't work out?|万一不成我该怎么办？|daily|请教/预案|long|work out|/wɜrk aʊt/|phr.成功",
"Is there a user manual I could look at?|有说明书我能看看吗？|daily|请教/资料|long|manual|/ˈmænjuəl/|n.手册",
"Could you show me how this machine works?|能演示一下这台机器怎么用吗？|daily|请教/操作|long|machine|/məˈʃiːn/|n.机器",
"Am I doing this the right way?|我这样做对吗？|daily|请教/确认|short|right way|/raɪt weɪ/|phr.正确方法",
"What would you do in my position?|你要是处在我的位置会怎么做？|daily|请教/建议|short|position|/pəˈzɪʃən/|n.处境",
"Do you have any tips for first-timers?|对新手你有什么小建议吗？|daily|请教/经验|long|tip|/tɪp/|n.小建议",
"How did you get into this hobby in the first place?|你当初是怎么入这个坑的？|daily|请教/经历|long|in the first place|/ɪn ðə fɜrst pleɪs/|phr.当初",
"First, press this button, then hold for three seconds.|先按这个键，然后长按三秒。|daily|说明/步骤|long|hold|/hoʊld/|v.长按",
"Make sure the lid is tightly closed before shaking.|摇之前确保盖子拧紧。|daily|说明/注意|short|lid|/lɪd/|n.盖子",
"Twist it to the left to open it.|往左拧就能打开。|daily|说明/操作|short|twist|/twɪst/|v.拧",
"Be careful not to touch the wet paint.|小心别碰到湿油漆。|daily|说明/提醒|short|paint|/peɪnt/|n.油漆",
"You have to press firmly for it to respond.|得用力按才会有反应。|daily|说明/操作|long|firmly|/ˈfɜrmli/|adv.用力地",
"Don't worry, it's perfectly safe to touch.|别担心，摸它完全安全。|daily|说明/安抚|long|perfectly|/ˈpɜrfɪktli/|adv.完全地",
"It works better if you warm it up first.|先预热一下效果更好。|daily|说明/技巧|short|warm up|/wɔrm ʌp/|phr.预热",
"Change the batteries when the light turns red.|灯变红时就该换电池了。|daily|说明/维护|short|battery|/ˈbætəri/|n.电池",
"Always unplug it before cleaning.|清洁前务必拔掉电源。|daily|说明/安全|short|unplug|/ʌnˈplʌɡ/|v.拔插头",
"The traffic light was red when I crossed.|我过马路时是红灯。|daily|描述/经历|short|traffic light|/ˈtræfɪk laɪt/|phr.红绿灯",
"I ran into an old classmate at the mall.|我在商场碰到老同学了。|daily|描述/经历|short|classmate|/ˈklæsmeɪt/|n.同学",
"The concert was totally worth the ticket price.|这场演唱会完全值回票价。|daily|描述/评价|long|worth|/wɜrθ/|adj.值得的",
"The movie didn't live up to the hype, honestly.|说实话，这电影名不副实。|daily|描述/评价|long|hype|/haɪp/|n.炒作",
"The food took forever to arrive but was delicious.|菜等了好久但味道不错。|daily|描述/经历|long|take forever|/teɪk fərˈɛvər/|phr.耗时很久",
"It was so crowded that we could barely move.|人多得我们几乎挪不动步。|daily|描述/场景|short|barely|/ˈbɛrli/|adv.几乎不",
"The sunset over the lake was breathtaking.|湖上的日落美得令人窒息。|daily|描述/景色|short|breathtaking|/ˈbrɛθˌteɪkɪŋ/|adj.美极了",
"I've never seen such a beautiful view before.|我从未见过这么美的景色。|daily|描述/景色|long|view|/vjuː/|n.景色",
"The whole trip exceeded my expectations.|整个旅程超出我的预期。|daily|描述/评价|short|exceed|/ɪkˈsiːd/|v.超出",
"Looking back, it was a wonderful decision.|回头看，那是个很棒的决定。|daily|反思/回顾|short|look back|/lʊk bæk/|phr.回顾",
"If I could do it over, I'd plan more carefully.|如果能重来，我会规划得更仔细。|daily|反思/假设|long|do over|/du ˈoʊvər/|phr.重来",
"I've learned a lot from that mistake.|我从那个错误中学到了很多。|daily|反思/教训|short|learn from|/lɜrn frʌm/|phr.从…学习",
"Hindsight is always twenty-twenty, isn't it?|事后诸葛谁都会当，不是吗？|daily|反思/感慨|long|hindsight|/ˈhaɪndsaɪt/|n.事后聪明",
"No regrets though, it was worth a try.|不过不后悔，值得一试。|daily|反思/态度|short|regret|/rɪˈɡrɛt/|n.后悔",
"Every failure teaches you something new.|每次失败都教你点新东西。|daily|反思/积极|short|failure|/ˈfeɪljər/|n.失败",
"It's never too late to start something new.|开始新事物永远不嫌晚。|daily|鼓励/开始|short|never too late|/ˈnɛvər tu leɪt/|phr.永远不晚",
"Take it one step at a time and don't rush.|一步一步来，别着急。|daily|鼓励/耐心|long|one step at a time|/wʌn stɛp ət ə taɪm/|phr.一步一步",
"You never know until you try, right?|不试试怎么知道，对吧？|daily|鼓励/尝试|short|never know|/ˈnɛvər noʊ/|phr.不知道",
"Believe in yourself a little more.|再多相信自己一点。|daily|鼓励/自信|short|believe in|/bɪˈliːv ɪn/|phr.相信",
"You're closer to your goal than you think.|你比想象中更接近目标。|daily|鼓励/肯定|short|goal|/ɡoʊl/|n.目标",
"Small steps every day add up big time.|每天一小步，累积成大跨越。|daily|鼓励/坚持|short|add up|/æd ʌp/|phr.累积",
"Don't sell yourself short, you're doing fine.|别妄自菲薄，你做得挺好。|daily|鼓励/肯定|long|sell short|/sɛl ʃɔrt/|phr.低估自己",
"Rest if you must, but don't you quit.|累了可以歇，但别放弃。|daily|鼓励/坚持|short|quit|/kwɪt/|v.放弃",
"Let's celebrate your progress so far.|咱们庆祝一下你目前的进步。|daily|鼓励/庆祝|short|progress|/ˈprɑɡrɛs/|n.进步",
"I knew you could pull it off!|我就知道你能成！|daily|夸赞/成就|short|pull off|/pʊl ɔf/|phr.成功做成",
"You've really outdone yourself this time.|你这次真是超常发挥了。|daily|夸赞/成就|short|outdo|/ˌaʊtˈduː/|v.超越",
"Couldn't be happier for you, congrats!|真替你高兴，恭喜！|daily|祝贺/祝福|short|congrats|/kənˈɡræts/|n.恭喜",
"Here's to many more wins ahead!|为今后更多的胜利干杯！|daily|祝贺/祝福|short|here's to|/hɪrz tuː/|phr.为…干杯",
"All the best with your new chapter.|祝你新篇章一切顺利。|daily|祝福/展望|short|all the best|/ɔl ðə bɛst/|phr.一切顺利",
]
